package three.js.editor.js.commands;

import AddObjectCommand from './AddObjectCommand';
import AddScriptCommand from './AddScriptCommand';
import MoveObjectCommand from './MoveObjectCommand';
import MultiCmdsCommand from './MultiCmdsCommand';
import RemoveObjectCommand from './RemoveObjectCommand';
import RemoveScriptCommand from './RemoveScriptCommand';
import SetColorCommand from './SetColorCommand';
import SetGeometryCommand from './SetGeometryCommand';
import SetGeometryValueCommand from './SetGeometryValueCommand';
import SetMaterialColorCommand from './SetMaterialColorCommand';
import SetMaterialCommand from './SetMaterialCommand';
import SetMaterialMapCommand from './SetMaterialMapCommand';
import SetMaterialRangeCommand from './SetMaterialRangeCommand';
import SetMaterialValueCommand from './SetMaterialValueCommand';
import SetMaterialVectorCommand from './SetMaterialVectorCommand';
import SetPositionCommand from './SetPositionCommand';
import SetRotationCommand from './SetRotationCommand';
import SetScaleCommand from './SetScaleCommand';
import SetSceneCommand from './SetSceneCommand';
import SetScriptValueCommand from './SetScriptValueCommand';
import SetUuidCommand from './SetUuidCommand';
import SetValueCommand from './SetValueCommand';

import AddObjectCommand;
import AddScriptCommand;
import MoveObjectCommand;
import MultiCmdsCommand;
import RemoveObjectCommand;
import RemoveScriptCommand;
import SetColorCommand;
import SetGeometryCommand;
import SetGeometryValueCommand;
import SetMaterialColorCommand;
import SetMaterialCommand;
import SetMaterialMapCommand;
import SetMaterialRangeCommand;
import SetMaterialValueCommand;
import SetMaterialVectorCommand;
import SetPositionCommand;
import SetRotationCommand;
import SetScaleCommand;
import SetSceneCommand;
import SetScriptValueCommand;
import SetUuidCommand;
import SetValueCommand;