class Strings {
    private static var values:StringMap<StringMap<String>> = {
        "en": {
            "prompt/file/open": "Any unsaved data will be lost. Are you sure?",
            "prompt/file/failedToOpenProject": "Failed to open project!",
            "prompt/file/export/noMeshSelected": "No Mesh selected!",
            "prompt/file/export/noObjectSelected": "No Object selected!",
            "prompt/script/remove": "Are you sure?",
            "prompt/history/clear": "The Undo/Redo History will be cleared. Are you sure?",
            "prompt/history/preserve": "The history will be preserved across sessions.\nThis can have an impact on performance when working with textures.",
            "prompt/history/forbid": "Undo/Redo disabled while scene is playing.",
            "command/AddObject": "Add Object",
            "command/AddScript": "Add Script",
            "command/MoveObject": "Move Object",
            "command/MultiCmds": "Multiple Changes",
            "command/RemoveObject": "Remove Object",
            "command/RemoveScript": "Remove Script",
            "command/SetColor": "Set Color",
            "command/SetGeometry": "Set Geometry",
            "command/SetGeometryValue": "Set Geometry Value",
            "command/SetMaterialColor": "Set Material Color",
            "command/SetMaterial": "Set Material",
            "command/SetMaterialMap": "Set Material Map",
            "command/SetMaterialRange": "Set Material Range",
            "command/SetMaterialValue": "Set Material Value",
            "command/SetMaterialVector": "Set Material Vector",
            "command/SetPosition": "Set Position",
            "command/SetRotation": "Set Rotation",
            "command/SetScale": "Set Scale",
            "command/SetScene": "Set Scene",
            "command/SetScriptValue": "Set Script Value",
            "command/SetUuid": "Set UUID",
            "command/SetValue": "Set Value",
            "menubar/file": "File",
            "menubar/file/newProject": "New Project",
            "menubar/file/newProject/empty": "Empty",
            "menubar/file/newProject/Arkanoid": "Arkanoid",
            "menubar/file/newProject/Camera": "Camera",
            "menubar/file/newProject/Particles": "Particles",
            "menubar/file/newProject/Pong": "Pong",
            "menubar/file/newProject/Shaders": "Shaders",
            "menubar/file/save": "Save",
            "menubar/file/open": "Open",
            "menubar/file/import": "Import",
            "menubar/file/export": "Export",
            "menubar/edit": "Edit",
            "menubar/edit/undo": "Undo (Ctrl+Z)",
            "menubar/edit/redo": "Redo (Ctrl+Shift+Z)",
            "menubar/edit/center": "Center",
            "menubar/edit/clone": "Clone",
            "menubar/edit/delete": "Delete (Del)",
            "menubar/add": "Add",
            "menubar/add/group": "Group",
            "menubar/add/mesh": "Mesh",
            "menubar/add/mesh/plane": "Plane",
            "menubar/add/mesh/box": "Box",
            "menubar/add/mesh/capsule": "Capsule",
            "menubar/add/mesh/circle": "Circle",
            "menubar/add/mesh/cylinder": "Cylinder",
            "menubar/add/mesh/ring": "Ring",
            "menubar/add/mesh/sphere": "Sphere",
            "menubar/add/mesh/dodecahedron": "Dodecahedron",
            "menubar/add/mesh/icosahedron": "Icosahedron",
            "menubar/add/mesh/octahedron": "Octahedron",
            "menubar/add/mesh/tetrahedron": "Tetrahedron",
            "menubar/add/mesh/torus": "Torus",
            "menubar/add/mesh/tube": "Tube",
            "menubar/add/mesh/torusknot": "TorusKnot",
            "menubar/add/mesh/lathe": "Lathe",
            "menubar/add/mesh/sprite": "Sprite",
            "menubar/add/light": "Light",
            "menubar/add/light/ambient": "Ambient",
            "menubar/add/light/directional": "Directional",
            "menubar/add/light/hemisphere": "Hemisphere",
            "menubar/add/light/point": "Point",
            "menubar/add/light/spot": "Spot",
            "menubar/add/camera": "Camera",
            "menubar/add/camera/perspective": "Perspective",
            "menubar/add/camera/orthographic": "Orthographic",
            "menubar/status/autosave": "autosave",
            "menubar/view": "View",
            "menubar/view/fullscreen": "Fullscreen",
            "menubar/help": "Help",
            "menubar/help/source_code": "Source Code",
            "menubar/help/icons": "Icon Pack",
            "menubar/help/about": "About",
            "menubar/help/manual": "Manual",
            "sidebar/animations": "Animations",
            "sidebar/animations/play": "Play",
            "sidebar/animations/stop": "Stop",
            "sidebar/animations/timescale": "Time Scale",
            "sidebar/scene": "Scene",
            "sidebar/scene/background": "Background",
            "sidebar/scene/environment": "Environment",
            "sidebar/scene/fog": "Fog",
            "sidebar/properties/object": "Object",
            "sidebar/properties/geometry": "Geometry",
            "sidebar/properties/material": "Material",
            "sidebar/properties/script": "Script",
            "sidebar/object/type": "Type",
            "sidebar/object/new": "New",
            "sidebar/object/uuid": "UUID",
            "sidebar/object/name": "Name",
            "sidebar/object/position": "Position",
            "sidebar/object/rotation": "Rotation",
            "sidebar/object/scale": "Scale",
            "sidebar/object/fov": "Fov",
            "sidebar/object/left": "Left",
            "sidebar/object/right": "Right",
            "sidebar/object/top": "Top",
            "sidebar/object/bottom": "Bottom",
            "sidebar/object/near": "Near",
            "sidebar/object/far": "Far",
            "sidebar/object/intensity": "Intensity",
            "sidebar/object/color": "Color",
            "sidebar/object/groundcolor": "Ground Color",
            "sidebar/object/distance": "Distance",
            "sidebar/object/angle": "Angle",
            "sidebar/object/penumbra": "Penumbra",
            "sidebar/object/decay": "Decay",
            "sidebar/object/shadow": "Shadow",
            "sidebar/object/shadowBias": "Shadow Bias",
            "sidebar/object/shadowNormalBias": "Shadow Normal Bias",
            "sidebar/object/shadowRadius": "Shadow Radius",
            "sidebar/object/cast": "cast",
            "sidebar/object/receive": "receive",
            "sidebar/object/visible": "Visible",
            "sidebar/object/frustumcull": "Frustum Cull",
            "sidebar/object/renderorder": "Render Order",
            "sidebar/object/userdata": "User data",
            "sidebar/object/export": "Export JSON",
            "sidebar/geometry/type": "Type",
            "sidebar/geometry/new": "New",
            "sidebar/geometry/uuid": "UUID",
            "sidebar/geometry/name": "Name",
            "sidebar/geometry/bounds": "Bounds",
            "sidebar/geometry/show_vertex_normals": "Show Vertex Normals",
            "sidebar/geometry/compute_vertex_normals": "Compute Vertex Normals",
            "sidebar/geometry/compute_vertex_tangents": "Compute Tangents",
            "sidebar/geometry/center": "Center",
            "sidebar/geometry/export": "Export JSON",
            "sidebar/geometry/box_geometry/width": "Width",
            "sidebar/geometry/box_geometry/height": "Height",
            "sidebar/geometry/box_geometry/depth": "Depth",
            "sidebar/geometry/box_geometry/widthseg": "Width Seg",
            "sidebar/geometry/box_geometry/heightseg": "Height Seg",
            "sidebar/geometry/box_geometry/depthseg": "Depth Seg",
            "sidebar/geometry/buffer_geometry/attributes": "Attributes",
            "sidebar/geometry/buffer_geometry/index": "index",
            "sidebar/geometry/buffer_geometry/morphAttributes": "Morph Attributes",
            "sidebar/geometry/buffer_geometry/morphRelative": "Morph Relative",
            "sidebar/geometry/capsule_geometry/radius": "Radius",
            "sidebar/geometry/capsule_geometry/length": "Length",
            "sidebar/geometry/capsule_geometry/capseg": "Cap Seg",
            "sidebar/geometry/capsule_geometry/radialseg": "Radial Seg",
            "sidebar/geometry/circle_geometry/radius": "Radius",
            "sidebar/geometry/circle_geometry/segments": "Segments",
            "sidebar/geometry/circle_geometry/thetastart": "Theta start",
            "sidebar/geometry/circle_geometry/thetalength": "Theta length",
            "sidebar/geometry/cylinder_geometry/radiustop": "Radius top",
            "sidebar/geometry/cylinder_geometry/radiusbottom": "Radius bottom",
            "sidebar/geometry/cylinder_geometry/height": "Height",
            "sidebar/geometry/cylinder_geometry/radialsegments": "Radial segments",
            "sidebar/geometry/cylinder_geometry/heightsegments": "Height segments",
            "sidebar/geometry/cylinder_geometry/openended": "Open ended",
            "sidebar/geometry/extrude_geometry/curveSegments": "Curve Segments",
            "sidebar/geometry/extrude_geometry/steps": "Steps",
            "sidebar/geometry/extrude_geometry/depth": "Depth",
            "sidebar/geometry/extrude_geometry/bevelEnabled": "Bevel",
            "sidebar/geometry/extrude_geometry/bevelThickness": "Thickness",
            "sidebar/geometry/extrude_geometry/bevelSize": "Size",
            "sidebar/geometry/extrude_geometry/bevelOffset": "Offset",
            "sidebar/geometry/extrude_geometry/bevelSegments": "Segments",
            "sidebar/geometry/extrude_geometry/shape": "Convert to Shape",
            "sidebar/geometry/dodecahedron_geometry/radius": "Radius",
            "sidebar/geometry/dodecahedron_geometry/detail": "Detail",
            "sidebar/geometry/icosahedron_geometry/radius": "Radius",
            "sidebar/geometry/icosahedron_geometry/detail": "Detail",
            "sidebar/geometry/octahedron_geometry/radius": "Radius",
            "sidebar/geometry/octahedron_geometry/detail": "Detail",
            "sidebar/geometry/tetrahedron_geometry/radius": "Radius",
            "sidebar/geometry/tetrahedron_geometry/detail": "Detail",
            "sidebar/geometry/lathe_geometry/segments": "Segments",
            "sidebar/geometry/lathe_geometry/phistart": "Phi start (°)",
            "sidebar/geometry/lathe_geometry/philength": "Phi length (°)",
            "sidebar/geometry/lathe_geometry/points": "Points",
            "sidebar/geometry/plane_geometry/width": "Width",
            "sidebar/geometry/plane_geometry/height": "Height",
            "sidebar/geometry/plane_geometry/widthsegments": "Width segments",
            "sidebar/geometry/plane_geometry/heightsegments": "Height segments",
            "sidebar/geometry/ring_geometry/innerRadius": "Inner radius",
            "sidebar/geometry/ring_geometry/outerRadius": "Outer radius",
            "sidebar/geometry/ring_geometry/thetaSegments": "Theta segments",
            "sidebar/geometry/ring_geometry/phiSegments": "Phi segments",
            "sidebar/geometry/ring_geometry/thetastart": "Theta start",
            "sidebar/geometry/ring_geometry/thetalength": "Theta length",
            "sidebar/geometry/shape_geometry/curveSegments": "Curve Segments",
            "sidebar/geometry/shape_geometry/extrude": "Extrude",
            "sidebar/geometry/sphere_geometry/radius": "Radius",
            "sidebar/geometry/sphere_geometry/widthsegments": "Width segments",
            "sidebar/geometry/sphere_geometry/heightsegments": "Height segments",
            "sidebar/geometry/sphere_geometry/phistart": "Phi start",
            "sidebar/geometry/sphere_geometry/philength": "Phi length",
            "sidebar/geometry/sphere_geometry/thetastart": "Theta start",
            "sidebar/geometry/sphere_geometry/thetalength": "Theta length",
            "sidebar/geometry/torus_geometry/radius": "Radius",
            "sidebar/geometry/torus_geometry/tube": "Tube",
            "sidebar/geometry/torus_geometry/radialsegments": "Radial segments",
            "sidebar/geometry/torus_geometry/tubularsegments": "Tubular segments",
            "sidebar/geometry/torus_geometry/arc": "Arc",
            "sidebar/geometry/torusKnot_geometry/radius": "Radius",
            "sidebar/geometry/torusKnot_geometry/tube": "Tube",
            "sidebar/geometry/torusKnot_geometry/tubularsegments": "Tubular segments",
            "sidebar/geometry/torusKnot_geometry/radialsegments": "Radial segments",
            "sidebar/geometry/torusKnot_geometry/p": "P",
            "sidebar/geometry/torusKnot_geometry/q": "Q",
            "sidebar/geometry/tube_geometry/path": "Path",
            "sidebar/geometry/tube_geometry/radius": "Radius",
            "sidebar/geometry/tube_geometry/tube": "Tube",
            "sidebar/geometry/tube_geometry/tubularsegments": "Tubular segments",
            "sidebar/geometry/tube_geometry/radialsegments": "Radial segments",
            "sidebar/geometry/tube_geometry/closed": "Closed",
            "sidebar/geometry/tube_geometry/curvetype": "Curve Type",
            "sidebar/geometry/tube_geometry/tension": "Tension",
            "sidebar/material/new": "New",
            "sidebar/material/copy": "Copy",
            "sidebar/material/paste": "Paste",
            "sidebar/material/slot": "Slot",
            "sidebar/material/type": "Type",
            "sidebar/material/uuid": "UUID",
            "sidebar/material/name": "Name",
            "sidebar/material/program": "Program",
            "sidebar/material/info": "Info",
            "sidebar/material/vertex": "Vert",
            "sidebar/material/fragment": "Frag",
            "sidebar/material/color": "Color",
            "sidebar/material/depthPacking": "Depth Packing",
            "sidebar/material/roughness": "Roughness",
            "sidebar/material/metalness": "Metalness",
            "sidebar/material/reflectivity": "Reflectivity",
            "sidebar/material/emissive": "Emissive",
            "sidebar/material/specular": "Specular",
            "sidebar/material/shininess": "Shininess",
            "sidebar/material/clearcoat": "Clearcoat",
            "sidebar/material/clearcoatroughness": "Clearcoat Roughness",
            "sidebar/material/dispersion": "Dispersion",
            "sidebar/material/ior": "IOR",
            "sidebar/material/iridescence": "Iridescence",
            "sidebar/material/iridescenceIOR": "Thin-Film IOR",
            "sidebar/material/iridescenceThicknessMax": "Thin-Film Thickness",
            "sidebar/material/sheen": "Sheen",
            "sidebar/material/sheenroughness": "Sheen Roughness",
            "sidebar/material/sheencolor": "Sheen Color",
            "sidebar/material/transmission": "Transmission",
            "sidebar/material/attenuationDistance": "Attenuation Distance",
            "sidebar/material/attenuationColor": "Attenuation Color",
            "sidebar/material/thickness": "Thickness",
            "sidebar/material/vertexcolors": "Vertex Colors",
            "sidebar/material/matcap": "Matcap",
            "sidebar/material/map": "Map",
            "sidebar/material/alphamap": "Alpha Map",
            "sidebar/material/bumpmap": "Bump Map",
            "sidebar/material/normalmap": "Normal Map",
            "sidebar/material/clearcoatmap": "Clearcoat Map",
            "sidebar/material/clearcoatnormalmap": "Clearcoat Normal Map",
            "sidebar/material/clearcoatroughnessmap": "Clearcoat Roughness Map",
            "sidebar/material/displacementmap": "Displace Map",
            "sidebar/material/roughnessmap": "Rough. Map",
            "sidebar/material/metalnessmap": "Metal. Map",
            "sidebar/material/specularmap": "Specular Map",
            "sidebar/material/iridescencemap": "Irid. Map",
            "sidebar/material/iridescencethicknessmap": "Thin-Film Thickness Map",
            "sidebar/material/sheencolormap": "Sheen Color Map",
            "sidebar/material/sheenroughnessmap": "Sheen Rough. Map",
            "sidebar/material/envmap": "Env Map",
            "sidebar/material/lightmap": "Light Map",
            "sidebar/material/aomap": "AO Map",
            "sidebar/material/emissivemap": "Em