import three.js.src.geometries.BoxGeometry;
import three.js.src.geometries.CapsuleGeometry;
import three.js.src.geometries.CircleGeometry;
import three.js.src.geometries.ConeGeometry;
import three.js.src.geometries.CylinderGeometry;
import three.js.src.geometries.DodecahedronGeometry;
import three.js.src.geometries.EdgesGeometry;
import three.js.src.geometries.ExtrudeGeometry;
import three.js.src.geometries.IcosahedronGeometry;
import three.js.src.geometries.LatheGeometry;
import three.js.src.geometries.OctahedronGeometry;
import three.js.src.geometries.PlaneGeometry;
import three.js.src.geometries.PolyhedronGeometry;
import three.js.src.geometries.RingGeometry;
import three.js.src.geometries.ShapeGeometry;
import three.js.src.geometries.SphereGeometry;
import three.js.src.geometries.TetrahedronGeometry;
import three.js.src.geometries.TorusGeometry;
import three.js.src.geometries.TorusKnotGeometry;
import three.js.src.geometries.TubeGeometry;
import three.js.src.geometries.WireframeGeometry;

export var BoxGeometry = BoxGeometry;
export var CapsuleGeometry = CapsuleGeometry;
export var CircleGeometry = CircleGeometry;
export var ConeGeometry = ConeGeometry;
export var CylinderGeometry = CylinderGeometry;
export var DodecahedronGeometry = DodecahedronGeometry;
export var EdgesGeometry = EdgesGeometry;
export var ExtrudeGeometry = ExtrudeGeometry;
export var IcosahedronGeometry = IcosahedronGeometry;
export var LatheGeometry = LatheGeometry;
export var OctahedronGeometry = OctahedronGeometry;
export var PlaneGeometry = PlaneGeometry;
export var PolyhedronGeometry = PolyhedronGeometry;
export var RingGeometry = RingGeometry;
export var ShapeGeometry = ShapeGeometry;
export var SphereGeometry = SphereGeometry;
export var TetrahedronGeometry = TetrahedronGeometry;
export var TorusGeometry = TorusGeometry;
export var TorusKnotGeometry = TorusKnotGeometry;
export var TubeGeometry = TubeGeometry;
export var WireframeGeometry = WireframeGeometry;