package;

import js.Browser.WebGl;

class ShaderChunk {
	public static var alphahash_fragment:String;
	public static var alphahash_pars_fragment:String;
	public static var alphamap_fragment:String;
	public static var alphamap_pars_fragment:String;
	public static var alphatest_fragment:String;
	public static var alphatest_pars_fragment:String;
	public static var aomap_fragment:String;
	public static var aomap_pars_fragment:String;
	public static var batching_pars_vertex:String;
	public static var batching_vertex:String;
	public static var begin_vertex:String;
	public static var beginnormal_vertex:String;
	public static var bsdfs:String;
	public static var iridescence_fragment:String;
	public static var bumpmap_pars_fragment:String;
	public static var clipping_planes_fragment:String;
	public static var clipping_planes_pars_fragment:String;
	public static var clipping_planes_pars_vertex:String;
	public static var clipping_planes_vertex:String;
	public static var color_fragment:String;
	public static var color_pars_fragment:String;
	public static var color_pars_vertex:String;
	public static var color_vertex:String;
	public static var common:String;
	public static var cube_uv_reflection_fragment:String;
	public static var defaultnormal_vertex:String;
	public static var displacementmap_pars_vertex:String;
	public static var displacementmap_vertex:String;
	public static var emissivemap_fragment:String;
	public static var emissivemap_pars_fragment:String;
	public static var colorspace_fragment:String;
	public static var colorspace_pars_fragment:String;
	public static var envmap_fragment:String;
	public static var envmap_common_pars_fragment:String;
	public static var envmap_pars_fragment:String;
	public static var envmap_pars_vertex:String;
	public static var envmap_vertex:String;
	public static var fog_vertex:String;
	public static var fog_pars_vertex:String;
	public static var fog_fragment:String;
	public static var fog_pars_fragment:String;
	public static var gradientmap_pars_fragment:String;
	public static var lightmap_pars_fragment:String;
	public static var lights_lambert_fragment:String;
	public static var lights_lambert_pars_fragment:String;
	public static var lights_pars_begin:String;
	public static var envmap_physical_pars_fragment:String;
	public static var lights_toon_fragment:String;
	public static var lights_toon_pars_fragment:String;
	public static var lights_phong_fragment:String;
	public static var lights_phong_pars_fragment:String;
	public static var lights_physical_fragment:String;
	public static var lights_physical_pars_fragment:String;
	public static var lights_fragment_begin:String;
	public static var lights_fragment_maps:String;
	public static var lights_fragment_end:String;
	public static var logdepthbuf_fragment:String;
	public static var logdepthbuf_pars_fragment:String;
	public static var logdepthbuf_pars_vertex:String;
	public static var logdepthbuf_vertex:String;
	public static var map_fragment:String;
	public static var map_pars_fragment:String;
	public static var map_particle_fragment:String;
	public static var map_particle_pars_fragment:String;
	public static var metalnessmap_fragment:String;
	public static var metalnessmap_pars_fragment:String;
	public static var morphinstance_vertex:String;
	public static var morphcolor_vertex:String;
	public static var morphnormal_vertex:String;
	public static var morphtarget_pars_vertex:String;
	public static var morphtarget_vertex:String;
	public static var normal_fragment_begin:String;
	public static var normal_fragment_maps:String;
	public static var normal_pars_fragment:String;
	public static var normal_pars_vertex:String;
	public static var normal_vertex:String;
	public static var normalmap_pars_fragment:String;
	public static var clearcoat_normal_fragment_begin:String;
	public static var clearcoat_normal_fragment_maps:String;
	public static var clearcoat_pars_fragment:String;
	public static var iridescence_pars_fragment:String;
	public static var opaque_fragment:String;
	public static var packing:String;
	public static var premultiplied_alpha_fragment:String;
	public static var project_vertex:String;
	public static var dithering_fragment:String;
	public static var dithering_pars_fragment:String;
	public static var roughnessmap_fragment:String;
	public static var roughnessmap_pars_fragment:String;
	public static var shadowmap_pars_fragment:String;
	public static var shadowmap_pars_vertex:String;
	public static var shadowmap_vertex:String;
	public static var shadowmask_pars_fragment:String;
	public static var skinbase_vertex:String;
	public static var skinning_pars_vertex:String;
	public static var skinning_vertex:String;
	public static var skinnormal_vertex:String;
	public static var specularmap_fragment:String;
	public static var specularmap_pars_fragment:String;
	public static var tonemapping_fragment:String;
	public static var tonemapping_pars_fragment:String;
	public static var transmission_fragment:String;
	public static var transmission_pars_fragment:String;
	public static var uv_pars_fragment:String;
	public static var uv_pars_vertex:String;
	public static var uv_vertex:String;
	public static var worldpos_vertex:String;

	public static var background_vert:String;
	public static var background_frag:String;
	public static var backgroundCube_vert:String;
	public static var backgroundCube_frag:String;
	public static var cube_vert:String;
	public static var cube_frag:String;
	public static var depth_vert:String;
	public static var depth_frag:String;
	public static var distanceRGBA_vert:String;
	public static var distanceRGBA_frag:String;
	public static var equirect_vert:String;
	public static var equirect_frag:String;
	public static var linedashed_vert:String;
	public static var linedashed_frag:String;
	public static var meshbasic_vert:String;
	public static var meshbasic_frag:String;
	public static var meshlambert_vert:String;
	public static var meshlambert_frag:String;
	public static var meshmatcap_vert:String;
	public static var meshmatcap_frag:String;
	public static var meshnormal_vert:String;
	public static var meshnormal_frag:String;
	public static var meshphong_vert:String;
	public static var meshphong_frag:String;
	public static var meshphysical_vert:String;
	public static var meshphysical_frag:String;
	public static var meshtoon_vert:String;
	public static var meshtoon_frag:String;
	public static var points_vert:String;
	public static var points_frag:String;
	public static var shadow_vert:String;
	public static var shadow_frag:String;
	public static var sprite_vert:String;
	public static var sprite_frag:String;

	public function new() {
		alphahash_fragment = null;
		alphahash_pars_fragment = null;
		alphamap_fragment = null;
		alphamap_pars_fragment = null;
		alphatest_fragment = null;
		alphatest_pars_fragment = null;
		aomap_fragment = null;
		aomap_pars_fragment = null;
		batching_pars_vertex = null;
		batching_vertex = null;
		begin_vertex = null;
		beginnormal_vertex = null;
		bsdfs = null;
		iridescence_fragment = null;
		bumpmap_pars_fragment = null;
		clipping_planes_fragment = null;
		clipping_planes_pars_fragment = null;
		clipping_planes_pars_vertex = null;
		clipping_planes_vertex = null;
		color_fragment = null;
		color_pars_fragment = null;
		color_pars_vertex = null;
		color_vertex = null;
		common = null;
		cube_uv_reflection_fragment = null;
		defaultnormal_vertex = null;
		displacementmap_pars_vertex = null;
		displacementmap_vertex = null;
		emissivemap_fragment = null;
		emissivemap_pars_fragment = null;
		colorspace_fragment = null;
		colorspace_pars_fragment = null;
		envmap_fragment = null;
		envmap_common_pars_fragment = null;
		envmap_pars_fragment = null;
		envmap_pars_vertex = null;
		envmap_vertex = null;
		fog_vertex = null;
		fog_pars_vertex = null;
		fog_fragment = null;
		fog_pars_fragment = null;
		gradientmap_pars_fragment = null;
		lightmap_pars_fragment = null;
		lights_lambert_fragment = null;
		lights_lambert_pars_fragment = null;
		lights_pars_begin = null;
		envmap_physical_pars_fragment = null;
		lights_toon_fragment = null;
		lights_toon_pars_fragment = null;
		lights_phong_fragment = null;
		lights_phong_pars_fragment = null;
		lights_physical_fragment = null;
		lights_physical_pars_fragment = null;
		lights_fragment_begin = null;
		lights_fragment_maps = null;
		lights_fragment_end = null;
		logdepthbuf_fragment = null;
		logdepthbuf_pars_fragment = null;
		logdepthbuf_pars_vertex = null;
		logdepthbuf_vertex = null;
		map_fragment = null;
		map_pars_fragment = null;
		map_particle_fragment = null;
		map_particle_pars_fragment = null;
		metalnessmap_fragment = null;
		metalnessmap_pars_fragment = null;
		morphinstance_vertex = null;
		morphcolor_vertex = null;
		morphnormal_vertex = null;
		morphtarget_pars_vertex = null;
		morphtarget_vertex = null;
		normal_fragment_begin = null;
		normal_fragment_maps = null;
		normal_pars_fragment = null;
		normal_pars_vertex = null;
		normal_vertex = null;
		normalmap_pars_fragment = null;
		clearcoat_normal_fragment_begin = null;
		clearcoat_normal_fragment_maps = null;
		clearcoat_pars_fragment = null;
		iridescence_pars_fragment = null;
		opaque_fragment = null;
		packing = null;
		premultiplied_alpha_fragment = null;
		project_vertex = null;
		dithering_fragment = null;
		dithering_pars_fragment = null;
		roughnessmap_fragment = null;
		roughnessmap_pars_fragment = null;
		shadowmap_pars_fragment = null;
		shadowmap_pars_vertex = null;
		shadowmap_vertex = null;
		shadowmask_pars_fragment = null;
		skinbase_vertex = null;
		skinning_pars_vertex = null;
		skinning_vertex = null;
		skinnormal_vertex = null;
		specularmap_fragment = null;
		specularmap_pars_fragment = null;
		tonemapping_fragment = null;
		tonemapping_pars_fragment = null;
		transmission_fragment = null;
		transmission_pars_fragment = null;
		uv_pars_fragment = null;
		uv_pars_vertex = null;
		uv_vertex = null;
		worldpos_vertex = null;

		background_vert = null;
		background_frag = null;
		backgroundCube_vert = null;
		backgroundCube_frag = null;
		cube_vert = null;
		cube_frag = null;
		depth_vert = null;
		depth_frag = null;
		distanceRGBA_vert = null;
		distanceRGBA_frag = null;
		equirect_vert = null;
		equirect_frag = null;
		linedashed_vert = null;
		linedashed_frag = null;
		meshbasic_vert = null;
		meshbasic_frag = null;
		meshlambert_vert = null;
		meshlambert_frag = null;
		meshmatcap_vert = null;
		meshmatcap_frag = null;
		meshnormal_vert = null;
		meshnormal_frag = null;
		meshphong_vert = null;
		meshphong_frag = null;
		meshphysical_vert = null;
		meshphysical_frag = null;
		meshtoon_vert = null;
		meshtoon_frag = null;
		points_vert = null;
		points_frag = null;
		shadow_vert = null;
		shadow_frag = null;
		sprite_vert = null;
		sprite_frag = null;
	}
}