package three.shader;

import ShaderChunk.AlphahashFragment;
import ShaderChunk.AlphahashParsFragment;
import ShaderChunk.AlphamapFragment;
import ShaderChunk.AlphamapParsFragment;
import ShaderChunk.AlphatestFragment;
import ShaderChunk.AlphatestParsFragment;
import ShaderChunk.AomapFragment;
import ShaderChunk.AomapParsFragment;
import ShaderChunk.BatchingParsVertex;
import ShaderChunk.BatchingVertex;
import ShaderChunk.BeginVertex;
import ShaderChunk.BeginnormalVertex;
import ShaderChunk.Bsdfs;
import ShaderChunk.IridescenceFragment;
import ShaderChunk.BumpmapParsFragment;
import ShaderChunk.ClippingPlanesFragment;
import ShaderChunk.ClippingPlanesParsFragment;
import ShaderChunk.ClippingPlanesParsVertex;
import ShaderChunk.ClippingPlanesVertex;
import ShaderChunk.ColorFragment;
import ShaderChunk.ColorParsFragment;
import ShaderChunk.ColorParsVertex;
import ShaderChunk.ColorVertex;
import ShaderChunk.Common;
import ShaderChunk.CubeUvReflectionFragment;
import ShaderChunk.DefaultnormalVertex;
import ShaderChunk.DisplacementmapParsVertex;
import ShaderChunk.DisplacementmapVertex;
import ShaderChunk.EmissivemapFragment;
import ShaderChunk.EmissivemapParsFragment;
import ShaderChunk.ColorspaceFragment;
import ShaderChunk.ColorspaceParsFragment;
import ShaderChunk.EnvmapFragment;
import ShaderChunk.EnvmapCommonParsFragment;
import ShaderChunk.EnvmapParsFragment;
import ShaderChunk.EnvmapParsVertex;
import ShaderChunk.EnvmapPhysicalParsFragment;
import ShaderChunk.EnvmapVertex;
import ShaderChunk.FogVertex;
import ShaderChunk.FogParsVertex;
import ShaderChunk.FogFragment;
import ShaderChunk.FogParsFragment;
import ShaderChunk.GradientmapParsFragment;
import ShaderChunk.LightmapParsFragment;
import ShaderChunk.LightsLambertFragment;
import ShaderChunk.LightsLambertParsFragment;
import ShaderChunk.LightsParsBegin;
import ShaderChunk.LightsToonFragment;
import ShaderChunk.LightsToonParsFragment;
import ShaderChunk.LightsPhongFragment;
import ShaderChunk.LightsPhongParsFragment;
import ShaderChunk.LightsPhysicalFragment;
import ShaderChunk.LightsPhysicalParsFragment;
import ShaderChunk.LightsFragmentBegin;
import ShaderChunk.LightsFragmentMaps;
import ShaderChunk.LightsFragmentEnd;
import ShaderChunk.LogdepthbufFragment;
import ShaderChunk.LogdepthbufParsFragment;
import ShaderChunk.LogdepthbufParsVertex;
import ShaderChunk.LogdepthbufVertex;
import ShaderChunk.MapFragment;
import ShaderChunk.MapParsFragment;
import ShaderChunk.MapParticleFragment;
import ShaderChunk.MapParticleParsFragment;
import ShaderChunk.MetalnessmapFragment;
import ShaderChunk.MetalnessmapParsFragment;
import ShaderChunk.MorphinstanceVertex;
import ShaderChunk.MorphcolorVertex;
import ShaderChunk.MorphnormalVertex;
import ShaderChunk.MorphtargetParsVertex;
import ShaderChunk.MorphtargetVertex;
import ShaderChunk.NormalFragmentBegin;
import ShaderChunk.NormalFragmentMaps;
import ShaderChunk.NormalParsFragment;
import ShaderChunk.NormalParsVertex;
import ShaderChunk.NormalVertex;
import ShaderChunk.NormalmapParsFragment;
import ShaderChunk.ClearcoatNormalFragmentBegin;
import ShaderChunk.ClearcoatNormalFragmentMaps;
import ShaderChunk.ClearcoatParsFragment;
import ShaderChunk.IridescenceParsFragment;
import ShaderChunk.OpaqueFragment;
import ShaderChunk.Packing;
import ShaderChunk.PremultipliedAlphaFragment;
import ShaderChunk.ProjectVertex;
import ShaderChunk.DitheringFragment;
import ShaderChunk.DitheringParsFragment;
import ShaderChunk.RoughnessmapFragment;
import ShaderChunk.RoughnessmapParsFragment;
import ShaderChunk.ShadowmapParsFragment;
import ShaderChunk.ShadowmapParsVertex;
import ShaderChunk.ShadowmapVertex;
import ShaderChunk.ShadowmaskParsFragment;
import ShaderChunk.SkinbaseVertex;
import ShaderChunk.SkinningParsVertex;
import ShaderChunk.SkinningVertex;
import ShaderChunk.SkinnormalVertex;
import ShaderChunk.SpecularmapFragment;
import ShaderChunk.SpecularmapParsFragment;
import ShaderChunk.TonemappingFragment;
import ShaderChunk.TonemappingParsFragment;
import ShaderChunk.TransmissionFragment;
import ShaderChunk.TransmissionParsFragment;
import ShaderChunk.UvParsFragment;
import ShaderChunk.UvParsVertex;
import ShaderChunk.UvVertex;
import ShaderChunk.WorldposVertex;

import ShaderLib.Background;
import ShaderLib.BackgroundCube;
import ShaderLib.Cube;
import ShaderLib.Depth;
import ShaderLib.DistanceRGBA;
import ShaderLib.Equirect;
import ShaderLib.Linedashed;
import ShaderLib.Meshbasic;
import ShaderLib.Meshlambert;
import ShaderLib.Meshmatcap;
import ShaderLib.Meshnormal;
import ShaderLib.Meshphong;
import ShaderLib.Meshphysical;
import ShaderLib.Meshtoon;
import ShaderLib.Points;
import ShaderLib.Shadow;
import ShaderLib.Sprite;

class ShaderChunk {
    public static var alphahash_fragment : String = AlphahashFragment.SHADER;
    public static var alphahash_pars_fragment : String = AlphahashParsFragment.SHADER;
    public static var alphamap_fragment : String = AlphamapFragment.SHADER;
    public static var alphamap_pars_fragment : String = AlphamapParsFragment.SHADER;
    public static var alphatest_fragment : String = AlphatestFragment.SHADER;
    public static var alphatest_pars_fragment : String = AlphatestParsFragment.SHADER;
    public static var aomap_fragment : String = AomapFragment.SHADER;
    public static var aomap_pars_fragment : String = AomapParsFragment.SHADER;
    public static var batching_pars_vertex : String = BatchingParsVertex.SHADER;
    public static var batching_vertex : String = BatchingVertex.SHADER;
    public static var begin_vertex : String = BeginVertex.SHADER;
    public static var beginnormal_vertex : String = BeginnormalVertex.SHADER;
    public static var bsdfs : String = Bsdfs.SHADER;
    public static var iridescence_fragment : String = IridescenceFragment.SHADER;
    public static var bumpmap_pars_fragment : String = BumpmapParsFragment.SHADER;
    public static var clipping_planes_fragment : String = ClippingPlanesFragment.SHADER;
    public static var clipping_planes_pars_fragment : String = ClippingPlanesParsFragment.SHADER;
    public static var clipping_planes_pars_vertex : String = ClippingPlanesParsVertex.SHADER;
    public static var clipping_planes_vertex : String = ClippingPlanesVertex.SHADER;
    public static var color_fragment : String = ColorFragment.SHADER;
    public static var color_pars_fragment : String = ColorParsFragment.SHADER;
    public static var color_pars_vertex : String = ColorParsVertex.SHADER;
    public static var color_vertex : String = ColorVertex.SHADER;
    public static var common : String = Common.SHADER;
    public static var cube_uv_reflection_fragment : String = CubeUvReflectionFragment.SHADER;
    public static var defaultnormal_vertex : String = DefaultnormalVertex.SHADER;
    public static var displacementmap_pars_vertex : String = DisplacementmapParsVertex.SHADER;
    public static var displacementmap_vertex : String = DisplacementmapVertex.SHADER;
    public static var emissivemap_fragment : String = EmissivemapFragment.SHADER;
    public static var emissivemap_pars_fragment : String = EmissivemapParsFragment.SHADER;
    public static var colorspace_fragment : String = ColorspaceFragment.SHADER;
    public static var colorspace_pars_fragment : String = ColorspaceParsFragment.SHADER;
    public static var envmap_fragment : String = EnvmapFragment.SHADER;
    public static var envmap_common_pars_fragment : String = EnvmapCommonParsFragment.SHADER;
    public static var envmap_pars_fragment : String = EnvmapParsFragment.SHADER;
    public static var envmap_pars_vertex : String = EnvmapParsVertex.SHADER;
    public static var envmap_physical_pars_fragment : String = EnvmapPhysicalParsFragment.SHADER;
    public static var envmap_vertex : String = EnvmapVertex.SHADER;
    public static var fog_vertex : String = FogVertex.SHADER;
    public static var fog_pars_vertex : String = FogParsVertex.SHADER;
    public static var fog_fragment : String = FogFragment.SHADER;
    public static var fog_pars_fragment : String = FogParsFragment.SHADER;
    public static var gradientmap_pars_fragment : String = GradientmapParsFragment.SHADER;
    public static var lightmap_pars_fragment : String = LightmapParsFragment.SHADER;
    public static var lights_lambert_fragment : String = LightsLambertFragment.SHADER;
    public static var lights_lambert_pars_fragment : String = LightsLambertParsFragment.SHADER;
    public static var lights_pars_begin : String = LightsParsBegin.SHADER;
    public static var lights_toon_fragment : String = LightsToonFragment.SHADER;
    public static var lights_toon_pars_fragment : String = LightsToonParsFragment.SHADER;
    public static var lights_phong_fragment : String = LightsPhongFragment.SHADER;
    public static var lights_phong_pars_fragment : String = LightsPhongParsFragment.SHADER;
    public static var lights_physical_fragment : String = LightsPhysicalFragment.SHADER;
    public static var lights_physical_pars_fragment : String = LightsPhysicalParsFragment.SHADER;
    public static var lights_fragment_begin : String = LightsFragmentBegin.SHADER;
    public static var lights_fragment_maps : String = LightsFragmentMaps.SHADER;
    public static var lights_fragment_end : String = LightsFragmentEnd.SHADER;
    public static var logdepthbuf_fragment : String = LogdepthbufFragment.SHADER;
    public static var logdepthbuf_pars_fragment : String = LogdepthbufParsFragment.SHADER;
    public static var logdepthbuf_pars_vertex : String = LogdepthbufParsVertex.SHADER;
    public static var logdepthbuf_vertex : String = LogdepthbufVertex.SHADER;
    public static var map_fragment : String = MapFragment.SHADER;
    public static var map_pars_fragment : String = MapParsFragment.SHADER;
    public static var map_particle_fragment : String = MapParticleFragment.SHADER;
    public static var map_particle_pars_fragment : String = MapParticleParsFragment.SHADER;
    public static var metalnessmap_fragment : String = MetalnessmapFragment.SHADER;
    public static var metalnessmap_pars_fragment : String = MetalnessmapParsFragment.SHADER;
    public static var morphinstance_vertex : String = MorphinstanceVertex.SHADER;
    public static var morphcolor_vertex : String = MorphcolorVertex.SHADER;
    public static var morphnormal_vertex : String = MorphnormalVertex.SHADER;
    public static var morphtarget_pars_vertex : String = MorphtargetParsVertex.SHADER;
    public static var morphtarget_vertex : String = MorphtargetVertex.SHADER;
    public static var normal_fragment_begin : String = NormalFragmentBegin.SHADER;
    public static var normal_fragment_maps : String = NormalFragmentMaps.SHADER;
    public static var normal_pars_fragment : String = NormalParsFragment.SHADER;
    public static var normal_pars_vertex : String = NormalParsVertex.SHADER;
    public static var normal_vertex : String = NormalVertex.SHADER;
    public static var normalmap_pars_fragment : String = NormalmapParsFragment.SHADER;
    public static var clearcoat_normal_fragment_begin : String = ClearcoatNormalFragmentBegin.SHADER;
    public static var clearcoat_normal_fragment_maps : String = ClearcoatNormalFragmentMaps.SHADER;
    public static var clearcoat_pars_fragment : String = ClearcoatParsFragment.SHADER;
    public static var iridescence_pars_fragment : String = IridescenceParsFragment.SHADER;
    public static var opaque_fragment : String = OpaqueFragment.SHADER;
    public static var packing : String = Packing.SHADER;
    public static var premultiplied_alpha_fragment : String = PremultipliedAlphaFragment.SHADER;
    public static var project_vertex : String = ProjectVertex.SHADER;
    public static var dithering_fragment : String = DitheringFragment.SHADER;
    public static var dithering_pars_fragment : String = DitheringParsFragment.SHADER;
    public static var roughnessmap_fragment : String = RoughnessmapFragment.SHADER;
    public static var roughnessmap_pars_fragment : String = RoughnessmapParsFragment.SHADER;
    public static var shadowmap_pars_fragment : String = ShadowmapParsFragment.SHADER;
    public static var shadowmap_pars_vertex : String = ShadowmapParsVertex.SHADER;
    public static var shadowmap_vertex : String = ShadowmapVertex.SHADER;
    public static var shadowmask_pars_fragment : String = ShadowmaskParsFragment.SHADER;
    public static var skinbase_vertex : String = SkinbaseVertex.SHADER;
    public static var skinning_pars_vertex : String = SkinningParsVertex.SHADER;
    public static var skinning_vertex : String = SkinningVertex.SHADER;
    public static var skinnormal_vertex : String = SkinnormalVertex.SHADER;
    public static var specularmap_fragment : String = SpecularmapFragment.SHADER;
    public static var specularmap_pars_fragment : String = SpecularmapParsFragment.SHADER;
    public static var tonemapping_fragment : String = TonemappingFragment.SHADER;
    public static var tonemapping_pars_fragment : String = TonemappingParsFragment.SHADER;
    public static var transmission_fragment : String = TransmissionFragment.SHADER;
    public static var transmission_pars_fragment : String = TransmissionParsFragment.SHADER;
    public static var uv_pars_fragment : String = UvParsFragment.SHADER;
    public static var uv_pars_vertex : String = UvParsVertex.SHADER;
    public static var uv_vertex : String = UvVertex.SHADER;
    public static var worldpos_vertex : String = WorldposVertex.SHADER;

    public static var background_vert : String = Background.VERTEX;
    public static var background_frag : String = Background.FRAGMENT;
    public static var backgroundCube_vert : String = BackgroundCube.VERTEX;
    public static var backgroundCube_frag : String = BackgroundCube.FRAGMENT;
    public static var cube_vert : String = Cube.VERTEX;
    public static var cube_frag : String = Cube.FRAGMENT;
    public static var depth_vert : String = Depth.VERTEX;
    public static var depth_frag : String = Depth.FRAGMENT;
    public static var distanceRGBA_vert : String = DistanceRGBA.VERTEX;
    public static var distanceRGBA_frag : String = DistanceRGBA.FRAGMENT;
    public static var equirect_vert : String = Equirect.VERTEX;
    public static var equirect_frag : String = Equirect.FRAGMENT;
    public static var linedashed_vert : String = Linedashed.VERTEX;
    public static var linedashed_frag : String = Linedashed.FRAGMENT;
    public static var meshbasic_vert : String = Meshbasic.VERTEX;
    public static var meshbasic_frag : String = Meshbasic.FRAGMENT;
    public static var meshlambert_vert : String = Meshlambert.VERTEX;
    public static var meshlambert_frag : String = Meshlambert.FRAGMENT;
    public static var meshmatcap_vert : String = Meshmatcap.VERTEX;
    public static var meshmatcap_frag : String = Meshmatcap.FRAGMENT;
    public static var meshnormal_vert : String = Meshnormal.VERTEX;
    public static var meshnormal_frag : String = Meshnormal.FRAGMENT;
    public static var meshphong_vert : String = Meshphong.VERTEX;
    public static var meshphong_frag : String = Meshphong.FRAGMENT;
    public static var meshphysical_vert : String = Meshphysical.VERTEX;
    public static var meshphysical_frag : String = Meshphysical.FRAGMENT;
    public static var meshtoon_vert : String = Meshtoon.VERTEX;
    public static var meshtoon_frag : String = Meshtoon.FRAGMENT;
    public static var points_vert : String = Points.VERTEX;
    public static var points_frag : String = Points.FRAGMENT;
    public static var shadow_vert : String = Shadow.VERTEX;
    public static var shadow_frag : String = Shadow.FRAGMENT;
    public static var sprite_vert : String = Sprite.VERTEX;
    public static var sprite_frag : String = Sprite.FRAGMENT;
}