import ShaderChunk.alphahash_fragment;
import ShaderChunk.alphahash_pars_fragment;
import ShaderChunk.alphamap_fragment;
import ShaderChunk.alphamap_pars_fragment;
import ShaderChunk.alphatest_fragment;
import ShaderChunk.alphatest_pars_fragment;
import ShaderChunk.aomap_fragment;
import ShaderChunk.aomap_pars_fragment;
import ShaderChunk.batching_pars_vertex;
import ShaderChunk.batching_vertex;
import ShaderChunk.begin_vertex;
import ShaderChunk.beginnormal_vertex;
import ShaderChunk.bsdfs;
import ShaderChunk.iridescence_fragment;
import ShaderChunk.bumpmap_pars_fragment;
import ShaderChunk.clipping_planes_fragment;
import ShaderChunk.clipping_planes_pars_fragment;
import ShaderChunk.clipping_planes_pars_vertex;
import ShaderChunk.clipping_planes_vertex;
import ShaderChunk.color_fragment;
import ShaderChunk.color_pars_fragment;
import ShaderChunk.color_pars_vertex;
import ShaderChunk.color_vertex;
import ShaderChunk.common;
import ShaderChunk.cube_uv_reflection_fragment;
import ShaderChunk.defaultnormal_vertex;
import ShaderChunk.displacementmap_pars_vertex;
import ShaderChunk.displacementmap_vertex;
import ShaderChunk.emissivemap_fragment;
import ShaderChunk.emissivemap_pars_fragment;
import ShaderChunk.colorspace_fragment;
import ShaderChunk.colorspace_pars_fragment;
import ShaderChunk.envmap_fragment;
import ShaderChunk.envmap_common_pars_fragment;
import ShaderChunk.envmap_pars_fragment;
import ShaderChunk.envmap_pars_vertex;
import ShaderChunk.envmap_vertex;
import ShaderChunk.fog_vertex;
import ShaderChunk.fog_pars_vertex;
import ShaderChunk.fog_fragment;
import ShaderChunk.fog_pars_fragment;
import ShaderChunk.gradientmap_pars_fragment;
import ShaderChunk.lightmap_pars_fragment;
import ShaderChunk.lights_lambert_fragment;
import ShaderChunk.lights_lambert_pars_fragment;
import ShaderChunk.lights_pars_begin;
import ShaderChunk.envmap_physical_pars_fragment;
import ShaderChunk.lights_toon_fragment;
import ShaderChunk.lights_toon_pars_fragment;
import ShaderChunk.lights_phong_fragment;
import ShaderChunk.lights_phong_pars_fragment;
import ShaderChunk.lights_physical_fragment;
import ShaderChunk.lights_physical_pars_fragment;
import ShaderChunk.lights_fragment_begin;
import ShaderChunk.lights_fragment_maps;
import ShaderChunk.lights_fragment_end;
import ShaderChunk.logdepthbuf_fragment;
import ShaderChunk.logdepthbuf_pars_fragment;
import ShaderChunk.logdepthbuf_pars_vertex;
import ShaderChunk.logdepthbuf_vertex;
import ShaderChunk.map_fragment;
import ShaderChunk.map_pars_fragment;
import ShaderChunk.map_particle_fragment;
import ShaderChunk.map_particle_pars_fragment;
import ShaderChunk.metalnessmap_fragment;
import ShaderChunk.metalnessmap_pars_fragment;
import ShaderChunk.morphinstance_vertex;
import ShaderChunk.morphcolor_vertex;
import ShaderChunk.morphnormal_vertex;
import ShaderChunk.morphtarget_pars_vertex;
import ShaderChunk.morphtarget_vertex;
import ShaderChunk.normal_fragment_begin;
import ShaderChunk.normal_fragment_maps;
import ShaderChunk.normal_pars_fragment;
import ShaderChunk.normal_pars_vertex;
import ShaderChunk.normal_vertex;
import ShaderChunk.normalmap_pars_fragment;
import ShaderChunk.clearcoat_normal_fragment_begin;
import ShaderChunk.clearcoat_normal_fragment_maps;
import ShaderChunk.clearcoat_pars_fragment;
import ShaderChunk.iridescence_pars_fragment;
import ShaderChunk.opaque_fragment;
import ShaderChunk.packing;
import ShaderChunk.premultiplied_alpha_fragment;
import ShaderChunk.project_vertex;
import ShaderChunk.dithering_fragment;
import ShaderChunk.dithering_pars_fragment;
import ShaderChunk.roughnessmap_fragment;
import ShaderChunk.roughnessmap_pars_fragment;
import ShaderChunk.shadowmap_pars_fragment;
import ShaderChunk.shadowmap_pars_vertex;
import ShaderChunk.shadowmap_vertex;
import ShaderChunk.shadowmask_pars_fragment;
import ShaderChunk.skinbase_vertex;
import ShaderChunk.skinning_pars_vertex;
import ShaderChunk.skinning_vertex;
import ShaderChunk.skinnormal_vertex;
import ShaderChunk.specularmap_fragment;
import ShaderChunk.specularmap_pars_fragment;
import ShaderChunk.tonemapping_fragment;
import ShaderChunk.tonemapping_pars_fragment;
import ShaderChunk.transmission_fragment;
import ShaderChunk.transmission_pars_fragment;
import ShaderChunk.uv_pars_fragment;
import ShaderChunk.uv_pars_vertex;
import ShaderChunk.uv_vertex;
import ShaderChunk.worldpos_vertex;

import background.vertex;
import background.fragment;
import backgroundCube.vertex;
import backgroundCube.fragment;
import cube.vertex;
import cube.fragment;
import depth.vertex;
import depth.fragment;
import distanceRGBA.vertex;
import distanceRGBA.fragment;
import equirect.vertex;
import equirect.fragment;
import linedashed.vertex;
import linedashed.fragment;
import meshbasic.vertex;
import meshbasic.fragment;
import meshlambert.vertex;
import meshlambert.fragment;
import meshmatcap.vertex;
import meshmatcap.fragment;
import meshnormal.vertex;
import meshnormal.fragment;
import meshphong.vertex;
import meshphong.fragment;
import meshphysical.vertex;
import meshphysical.fragment;
import meshtoon.vertex;
import meshtoon.fragment;
import points.vertex;
import points.fragment;
import shadow.vertex;
import shadow.fragment;
import sprite.vertex;
import sprite.fragment;

class ShaderChunk {
    public static var alphahash_fragment:String = alphahash_fragment;
    public static var alphahash_pars_fragment:String = alphahash_pars_fragment;
    public static var alphamap_fragment:String = alphamap_fragment;
    public static var alphamap_pars_fragment:String = alphamap_pars_fragment;
    public static var alphatest_fragment:String = alphatest_fragment;
    public static var alphatest_pars_fragment:String = alphatest_pars_fragment;
    public static var aomap_fragment:String = aomap_fragment;
    public static var aomap_pars_fragment:String = aomap_pars_fragment;
    public static var batching_pars_vertex:String = batching_pars_vertex;
    public static var batching_vertex:String = batching_vertex;
    public static var begin_vertex:String = begin_vertex;
    public static var beginnormal_vertex:String = beginnormal_vertex;
    public static var bsdfs:String = bsdfs;
    public static var iridescence_fragment:String = iridescence_fragment;
    public static var bumpmap_pars_fragment:String = bumpmap_pars_fragment;
    public static var clipping_planes_fragment:String = clipping_planes_fragment;
    public static var clipping_planes_pars_fragment:String = clipping_planes_pars_fragment;
    public static var clipping_planes_pars_vertex:String = clipping_planes_pars_vertex;
    public static var clipping_planes_vertex:String = clipping_planes_vertex;
    public static var color_fragment:String = color_fragment;
    public static var color_pars_fragment:String = color_pars_fragment;
    public static var color_pars_vertex:String = color_pars_vertex;
    public static var color_vertex:String = color_vertex;
    public static var common:String = common;
    public static var cube_uv_reflection_fragment:String = cube_uv_reflection_fragment;
    public static var defaultnormal_vertex:String = defaultnormal_vertex;
    public static var displacementmap_pars_vertex:String = displacementmap_pars_vertex;
    public static var displacementmap_vertex:String = displacementmap_vertex;
    public static var emissivemap_fragment:String = emissivemap_fragment;
    public static var emissivemap_pars_fragment:String = emissivemap_pars_fragment;
    public static var colorspace_fragment:String = colorspace_fragment;
    public static var colorspace_pars_fragment:String = colorspace_pars_fragment;
    public static var envmap_fragment:String = envmap_fragment;
    public static var envmap_common_pars_fragment:String = envmap_common_pars_fragment;
    public static var envmap_pars_fragment:String = envmap_pars_fragment;
    public static var envmap_pars_vertex:String = envmap_pars_vertex;
    public static var envmap_vertex:String = envmap_vertex;
    public static var fog_vertex:String = fog_vertex;
    public static var fog_pars_vertex:String = fog_pars_vertex;
    public static var fog_fragment:String = fog_fragment;
    public static var fog_pars_fragment:String = fog_pars_fragment;
    public static var gradientmap_pars_fragment:String = gradientmap_pars_fragment;
    public static var lightmap_pars_fragment:String = lightmap_pars_fragment;
    public static var lights_lambert_fragment:String = lights_lambert_fragment;
    public static var lights_lambert_pars_fragment:String = lights_lambert_pars_fragment;
    public static var lights_pars_begin:String = lights_pars_begin;
    public static var envmap_physical_pars_fragment:String = envmap_physical_pars_fragment;
    public static var lights_toon_fragment:String = lights_toon_fragment;
    public static var lights_toon_pars_fragment:String = lights_toon_pars_fragment;
    public static var lights_phong_fragment:String = lights_phong_fragment;
    public static var lights_phong_pars_fragment:String = lights_phong_pars_fragment;
    public static var lights_physical_fragment:String = lights_physical_fragment;
    public static var lights_physical_pars_fragment:String = lights_physical_pars_fragment;
    public static var lights_fragment_begin:String = lights_fragment_begin;
    public static var lights_fragment_maps:String = lights_fragment_maps;
    public static var lights_fragment_end:String = lights_fragment_end;
    public static var logdepthbuf_fragment:String = logdepthbuf_fragment;
    public static var logdepthbuf_pars_fragment:String = logdepthbuf_pars_fragment;
    public static var logdepthbuf_pars_vertex:String = logdepthbuf_pars_vertex;
    public static var logdepthbuf_vertex:String = logdepthbuf_vertex;
    public static var map_fragment:String = map_fragment;
    public static var map_pars_fragment:String = map_pars_fragment;
    public static var map_particle_fragment:String = map_particle_fragment;
    public static var map_particle_pars_fragment:String = map_particle_pars_fragment;
    public static var metalnessmap_fragment:String = metalnessmap_fragment;
    public static var metalnessmap_pars_fragment:String = metalnessmap_pars_fragment;
    public static var morphinstance_vertex:String = morphinstance_vertex;
    public static var morphcolor_vertex:String = morphcolor_vertex;
    public static var morphnormal_vertex:String = morphnormal_vertex;
    public static var morphtarget_pars_vertex:String = morphtarget_pars_vertex;
    public static var morphtarget_vertex:String = morphtarget_vertex;
    public static var normal_fragment_begin:String = normal_fragment_begin;
    public static var normal_fragment_maps:String = normal_fragment_maps;
    public static var normal_pars_fragment:String = normal_pars_fragment;
    public static var normal_pars_vertex:String = normal_pars_vertex;
    public static var normal_vertex:String = normal_vertex;
    public static var normalmap_pars_fragment:String = normalmap_pars_fragment;
    public static var clearcoat_normal_fragment_begin:String = clearcoat_normal_fragment_begin;
    public static var clearcoat_normal_fragment_maps:String = clearcoat_normal_fragment_maps;
    public static var clearcoat_pars_fragment:String = clearcoat_pars_fragment;
    public static var iridescence_pars_fragment:String = iridescence_pars_fragment;
    public static var opaque_fragment:String = opaque_fragment;
    public static var packing:String = packing;
    public static var premultiplied_alpha_fragment:String = premultiplied_alpha_fragment;
    public static var project_vertex:String = project_vertex;
    public static var dithering_fragment:String = dithering_fragment;
    public static var dithering_pars_fragment:String = dithering_pars_fragment;
    public static var roughnessmap_fragment:String = roughnessmap_fragment;
    public static var roughnessmap_pars_fragment:String = roughnessmap_pars_fragment;
    public static var shadowmap_pars_fragment:String = shadowmap_pars_fragment;
    public static var shadowmap_pars_vertex:String = shadowmap_pars_vertex;
    public static var shadowmap_vertex:String = shadowmap_vertex;
    public static var shadowmask_pars_fragment:String = shadowmask_pars_fragment;
    public static var skinbase_vertex:String = skinbase_vertex;
    public static var skinning_pars_vertex:String = skinning_pars_vertex;
    public static var skinning_vertex:String = skinning_vertex;
    public static var skinnormal_vertex:String = skinnormal_vertex;
    public static var specularmap_fragment:String = specularmap_fragment;
    public static var specularmap_pars_fragment:String = specularmap_pars_fragment;
    public static var tonemapping_fragment:String = tonemapping_fragment;
    public static var tonemapping_pars_fragment:String = tonemapping_pars_fragment;
    public static var transmission_fragment:String = transmission_fragment;
    public static var transmission_pars_fragment:String = transmission_pars_fragment;
    public static var uv_pars_fragment:String = uv_pars_fragment;
    public static var uv_pars_vertex:String = uv_pars_vertex;
    public static var uv_vertex:String = uv_vertex;
    public static var worldpos_vertex:String = worldpos_vertex;

    public static var background_vert:String = background.vertex;
    public static var background_frag:String = background.fragment;
    public static var backgroundCube_vert:String = backgroundCube.vertex;
    public static var backgroundCube_frag:String = backgroundCube.fragment;
    public static var cube_vert:String = cube.vertex;
    public static var cube_frag:String = cube.fragment;
    public static var depth_vert:String = depth.vertex;
    public static var depth_frag:String = depth.fragment;
    public static var distanceRGBA_vert:String = distanceRGBA.vertex;
    public static var distanceRGBA_frag:String = distanceRGBA.fragment;
    public static var equirect_vert:String = equirect.vertex;
    public static var equirect_frag:String = equirect.fragment;
    public static var linedashed_vert:String = linedashed.vertex;
    public static var linedashed_frag:String = linedashed.fragment;
    public static var meshbasic_vert:String = meshbasic.vertex;
    public static var meshbasic_frag:String = meshbasic.fragment;
    public static var meshlambert_vert:String = meshlambert.vertex;
    public static var meshlambert_frag:String = meshlambert.fragment;
    public static var meshmatcap_vert:String = meshmatcap.vertex;
    public static var meshmatcap_frag:String = meshmatcap.fragment;
    public static var meshnormal_vert:String = meshnormal.vertex;
    public static var meshnormal_frag:String = meshnormal.fragment;
    public static var meshphong_vert:String = meshphong.vertex;
    public static var meshphong_frag:String = meshphong.fragment;
    public static var meshphysical_vert:String = meshphysical.vertex;
    public static var meshphysical_frag:String = meshphysical.fragment;
    public static var meshtoon_vert:String = meshtoon.vertex;
    public static var meshtoon_frag:String = meshtoon.fragment;
    public static var points_vert:String = points.vertex;
    public static var points_frag:String = points.fragment;
    public static var shadow_vert:String = shadow.vertex;
    public static var shadow_frag:String = shadow.fragment;
    public static var sprite_vert:String = sprite.vertex;
    public static var sprite_frag:String = sprite.fragment;
}