Here is the equivalent Haxe code:
```
package renderers.shaders;

import alphahash_fragment from './ShaderChunk/alphahash_fragment.glsl.js';
import alphahash_pars_fragment from './ShaderChunk/alphahash_pars_fragment.glsl.js';
import alphamap_fragment from './ShaderChunk/alphamap_fragment.glsl.js';
import alphamap_pars_fragment from './ShaderChunk/alphamap_pars_fragment.glsl.js';
import alphatest_fragment from './ShaderChunk/alphatest_fragment.glsl.js';
import alphatest_pars_fragment from './ShaderChunk/alphatest_pars_fragment.glsl.js';
import aomap_fragment from './ShaderChunk/aomap_fragment.glsl.js';
import aomap_pars_fragment from './ShaderChunk/aomap_pars_fragment.glsl.js';
import batching_pars_vertex from './ShaderChunk/batching_pars_vertex.glsl.js';
import batching_vertex from './ShaderChunk/batching_vertex.glsl.js';
import begin_vertex from './ShaderChunk/begin_vertex.glsl.js';
import beginnormal_vertex from './ShaderChunk/beginnormal_vertex.glsl.js';
import bsdfs from './ShaderChunk/bsdfs.glsl.js';
import iridescence_fragment from './ShaderChunk/iridescence_fragment.glsl.js';
import bumpmap_pars_fragment from './ShaderChunk/bumpmap_pars_fragment.glsl.js';
import clipping_planes_fragment from './ShaderChunk/clipping_planes_fragment.glsl.js';
import clipping_planes_pars_fragment from './ShaderChunk/clipping_planes_pars_fragment.glsl.js';
import clipping_planes_pars_vertex from './ShaderChunk/clipping_planes_pars_vertex.glsl.js';
import clipping_planes_vertex from './ShaderChunk/clipping_planes_vertex.glsl.js';
import color_fragment from './ShaderChunk/color_fragment.glsl.js';
import color_pars_fragment from './ShaderChunk/color_pars_fragment.glsl.js';
import color_pars_vertex from './ShaderChunk/color_pars_vertex.glsl.js';
import color_vertex from './ShaderChunk/color_vertex.glsl.js';
import common from './ShaderChunk/common.glsl.js';
import cube_uv_reflection_fragment from './ShaderChunk/cube_uv_reflection_fragment.glsl.js';
import defaultnormal_vertex from './ShaderChunk/defaultnormal_vertex.glsl.js';
import displacementmap_pars_vertex from './ShaderChunk/displacementmap_pars_vertex.glsl.js';
import displacementmap_vertex from './ShaderChunk/displacementmap_vertex.glsl.js';
import emissivemap_fragment from './ShaderChunk/emissivemap_fragment.glsl.js';
import emissivemap_pars_fragment from './ShaderChunk/emissivemap_pars_fragment.glsl.js';
import colorspace_fragment from './ShaderChunk/colorspace_fragment.glsl.js';
import colorspace_pars_fragment from './ShaderChunk/colorspace_pars_fragment.glsl.js';
import envmap_fragment from './ShaderChunk/envmap_fragment.glsl.js';
import envmap_common_pars_fragment from './ShaderChunk/envmap_common_pars_fragment.glsl.js';
import envmap_pars_fragment from './ShaderChunk/envmap_pars_fragment.glsl.js';
import envmap_pars_vertex from './ShaderChunk/envmap_pars_vertex.glsl.js';
import envmap_vertex from './ShaderChunk/envmap_vertex.glsl.js';
import fog_vertex from './ShaderChunk/fog_vertex.glsl.js';
import fog_pars_vertex from './ShaderChunk/fog_pars_vertex.glsl.js';
import fog_fragment from './ShaderChunk/fog_fragment.glsl.js';
import fog_pars_fragment from './ShaderChunk/fog_pars_fragment.glsl.js';
import gradientmap_pars_fragment from './ShaderChunk/gradientmap_pars_fragment.glsl.js';
import lightmap_pars_fragment from './ShaderChunk/lightmap_pars_fragment.glsl.js';
import lights_lambert_fragment from './ShaderChunk/lights_lambert_fragment.glsl.js';
import lights_lambert_pars_fragment from './ShaderChunk/lights_lambert_pars_fragment.glsl.js';
import lights_pars_begin from './ShaderChunk/lights_pars_begin.glsl.js';
import envmap_physical_pars_fragment from './ShaderChunk/envmap_physical_pars_fragment.glsl.js';
import lights_toon_fragment from './ShaderChunk/lights_toon_fragment.glsl.js';
import lights_toon_pars_fragment from './ShaderChunk/lights_toon_pars_fragment.glsl.js';
import lights_phong_fragment from './ShaderChunk/lights_phong_fragment.glsl.js';
import lights_phong_pars_fragment from './ShaderChunk/lights_phong_pars_fragment.glsl.js';
import lights_physical_fragment from './ShaderChunk/lights_physical_fragment.glsl.js';
import lights_physical_pars_fragment from './ShaderChunk/lights_physical_pars_fragment.glsl.js';
import lights_fragment_begin from './ShaderChunk/lights_fragment_begin.glsl.js';
import lights_fragment_maps from './ShaderChunk/lights_fragment_maps.glsl.js';
import lights_fragment_end from './ShaderChunk/lights_fragment_end.glsl.js';
import logdepthbuf_fragment from './ShaderChunk/logdepthbuf_fragment.glsl.js';
import logdepthbuf_pars_fragment from './ShaderChunk/logdepthbuf_pars_fragment.glsl.js';
import logdepthbuf_pars_vertex from './ShaderChunk/logdepthbuf_pars_vertex.glsl.js';
import logdepthbuf_vertex from './ShaderChunk/logdepthbuf_vertex.glsl.js';
import map_fragment from './ShaderChunk/map_fragment.glsl.js';
import map_pars_fragment from './ShaderChunk/map_pars_fragment.glsl.js';
import map_particle_fragment from './ShaderChunk/map_particle_fragment.glsl.js';
import map_particle_pars_fragment from './ShaderChunk/map_particle_pars_fragment.glsl.js';
import metalnessmap_fragment from './ShaderChunk/metalnessmap_fragment.glsl.js';
import metalnessmap_pars_fragment from './ShaderChunk/metalnessmap_pars_fragment.glsl.js';
import morphinstance_vertex from './ShaderChunk/morphinstance_vertex.glsl.js';
import morphcolor_vertex from './ShaderChunk/morphcolor_vertex.glsl.js';
import morphnormal_vertex from './ShaderChunk/morphnormal_vertex.glsl.js';
import morphtarget_pars_vertex from './ShaderChunk/morphtarget_pars_vertex.glsl.js';
import morphtarget_vertex from './ShaderChunk/morphtarget_vertex.glsl.js';
import normal_fragment_begin from './ShaderChunk/normal_fragment_begin.glsl.js';
import normal_fragment_maps from './ShaderChunk/normal_fragment_maps.glsl.js';
import normal_pars_fragment from './ShaderChunk/normal_pars_fragment.glsl.js';
import normal_pars_vertex from './ShaderChunk/normal_pars_vertex.glsl.js';
import normal_vertex from './ShaderChunk/normal_vertex.glsl.js';
import normalmap_pars_fragment from './ShaderChunk/normalmap_pars_fragment.glsl.js';
import clearcoat_normal_fragment_begin from './ShaderChunk/clearcoat_normal_fragment_begin.glsl.js';
import clearcoat_normal_fragment_maps from './ShaderChunk/clearcoat_normal_fragment_maps.glsl.js';
import clearcoat_pars_fragment from './ShaderChunk/clearcoat_pars_fragment.glsl.js';
import iridescence_pars_fragment from './ShaderChunk/iridescence_pars_fragment.glsl.js';
import opaque_fragment from './ShaderChunk/opaque_fragment.glsl.js';
import packing from './ShaderChunk/packing.glsl.js';
import premultiplied_alpha_fragment from './ShaderChunk/premultiplied_alpha_fragment.glsl.js';
import project_vertex from './ShaderChunk/project_vertex.glsl.js';
import dithering_fragment from './ShaderChunk/dithering_fragment.glsl.js';
import dithering_pars_fragment from './ShaderChunk/dithering_pars_fragment.glsl.js';
import roughnessmap_fragment from './ShaderChunk/roughnessmap_fragment.glsl.js';
import roughnessmap_pars_fragment from './ShaderChunk/roughnessmap_pars_fragment.glsl.js';
import shadowmap_pars_fragment from './ShaderChunk/shadowmap_pars_fragment.glsl.js';
import shadowmap_pars_vertex from './ShaderChunk/shadowmap_pars_vertex.glsl.js';
import shadowmap_vertex from './ShaderChunk/shadowmap_vertex.glsl.js';
import shadowmask_pars_fragment from './ShaderChunk/shadowmask_pars_fragment.glsl.js';
import skinbase_vertex from './ShaderChunk/skinbase_vertex.glsl.js';
import skinning_pars_vertex from './ShaderChunk/skinning_pars_vertex.glsl.js';
import skinning_vertex from './ShaderChunk/skinning_vertex.glsl.js';
import skinnormal_vertex from './ShaderChunk/skinnormal_vertex.glsl.js';
import specularmap_fragment from './ShaderChunk/specularmap_fragment.glsl.js';
import specularmap_pars_fragment from './ShaderChunk/specularmap_pars_fragment.glsl.js';
import tonemapping_fragment from './ShaderChunk/tonemapping_fragment.glsl.js';
import tonemapping_pars_fragment from './ShaderChunk/tonemapping_pars_fragment.glsl.js';
import transmission_fragment from './ShaderChunk/transmission_fragment.glsl.js';
import transmission_pars_fragment from './ShaderChunk/transmission_pars_fragment.glsl.js';
import uv_pars_fragment from './ShaderChunk/uv_pars_fragment.glsl.js';
import uv_pars_vertex from './ShaderChunk/uv_pars_vertex.glsl.js';
import uv_vertex from './ShaderChunk/uv_vertex.glsl.js';
import worldpos_vertex from './ShaderChunk/worldpos_vertex.glsl.js';

import background from './ShaderLib/background.glsl.js';
import backgroundCube from './ShaderLib/backgroundCube.glsl.js';
import cube from './ShaderLib/cube.glsl.js';
import depth from './ShaderLib/depth.glsl.js';
import distanceRGBA from './ShaderLib/distanceRGBA.glsl.js';
import equirect from './ShaderLib/equirect.glsl.js';
import linedashed from './ShaderLib/linedashed.glsl.js';
import meshbasic from './ShaderLib/meshbasic.glsl.js';
import meshlambert from './ShaderLib/meshlambert.glsl.js';
import meshmatcap from './ShaderLib/meshmatcap.glsl.js';
import meshnormal from './ShaderLib/meshnormal.glsl.js';
import meshphong from './ShaderLib/meshphong.glsl.js';
import meshphysical from './ShaderLib/meshphysical.glsl.js';
import meshtoon from './ShaderLib/meshtoon.glsl.js';
import points from './ShaderLib/points.glsl.js';
import shadow from './ShaderLib/shadow.glsl.js';
import sprite from './ShaderLib/sprite.glsl.js';

class ShaderChunk {
    public static var alphahash_fragment:Dynamic = alphahash_fragment;
    public static var alphahash_pars_fragment:Dynamic = alphahash_pars_fragment;
    public static var alphamap_fragment:Dynamic = alphamap_fragment;
    public static var alphamap_pars_fragment:Dynamic = alphamap_pars_fragment;
    public static var alphatest_fragment:Dynamic = alphatest_fragment;
    public static var alphatest_pars_fragment:Dynamic = alphatest_pars_fragment;
    public static var aomap_fragment:Dynamic = aomap_fragment;
    public static var aomap_pars_fragment:Dynamic = aomap_pars_fragment;
    public static var batching_pars_vertex:Dynamic = batching_pars_vertex;
    public static var batching_vertex:Dynamic = batching_vertex;
    public static var begin_vertex:Dynamic = begin_vertex;
    public static var beginnormal_vertex:Dynamic = beginnormal_vertex;
    public static var bsdfs:Dynamic = bsdfs;
    public static var iridescence_fragment:Dynamic = iridescence_fragment;
    public static var bumpmap_pars_fragment:Dynamic = bumpmap_pars_fragment;
    public static var clipping_planes_fragment:Dynamic = clipping_planes_fragment;
    public static var clipping_planes_pars_fragment:Dynamic = clipping_planes_pars_fragment;
    public static var clipping_planes_pars_vertex:Dynamic = clipping_planes_pars_vertex;
    public static var clipping_planes_vertex:Dynamic = clipping_planes_vertex;
    public static var color_fragment:Dynamic = color_fragment;
    public static var color_pars_fragment:Dynamic = color_pars_fragment;
    public static var color_pars_vertex:Dynamic = color_pars_vertex;
    public static var color_vertex:Dynamic = color_vertex;
    public static var common:Dynamic = common;
    public static var cube_uv_reflection_fragment:Dynamic = cube_uv_reflection_fragment;
    public static var defaultnormal_vertex:Dynamic = defaultnormal_vertex;
    public static var displacementmap_pars_vertex:Dynamic = displacementmap_pars_vertex;
    public static var displacementmap_vertex:Dynamic = displacementmap_vertex;
    public static var emissivemap_fragment:Dynamic = emissivemap_fragment;
    public static var emissivemap_pars_fragment:Dynamic = emissivemap_pars_fragment;
    public static var colorspace_fragment:Dynamic = colorspace_fragment;
    public static var colorspace_pars_fragment:Dynamic = colorspace_pars_fragment;
    public static var envmap_fragment:Dynamic = envmap_fragment;
    public static var envmap_common_pars_fragment:Dynamic = envmap_common_pars_fragment;
    public static var envmap_pars_fragment:Dynamic = envmap_pars_fragment;
    public static var envmap_pars_vertex:Dynamic = envmap_pars_vertex;
    public static var envmap_vertex:Dynamic = envmap_vertex;
    public static var fog_vertex:Dynamic = fog_vertex;
    public static var fog_pars_vertex:Dynamic = fog_pars_vertex;
    public static var fog_fragment:Dynamic = fog_fragment;
    public static var fog_pars_fragment:Dynamic = fog_pars_fragment;
    public static var gradientmap_pars_fragment:Dynamic = gradientmap_pars_fragment;
    public static var lightmap_pars_fragment:Dynamic = lightmap_pars_fragment;
    public static var lights_lambert_fragment:Dynamic = lights_lambert_fragment;
    public static var lights_lambert_pars_fragment:Dynamic = lights_lambert_pars_fragment;
    public static var lights_pars_begin:Dynamic = lights_pars_begin;
    public static var envmap_physical_pars_fragment:Dynamic = envmap_physical_pars_fragment;
    public static var lights_toon_fragment:Dynamic = lights_toon_fragment;
    public static var lights_toon_pars_fragment:Dynamic = lights_toon_pars_fragment;
    public static var lights_phong_fragment:Dynamic = lights_phong_fragment;
    public static var lights_phong_pars_fragment:Dynamic = lights_phong_pars_fragment;
    public static var lights_physical_fragment:Dynamic = lights_physical_fragment;
    public static var lights_physical_pars_fragment:Dynamic = lights_physical_pars_fragment;
    public static var lights_fragment_begin:Dynamic = lights_fragment_begin;
    public static var lights_fragment_maps:Dynamic = lights_fragment_maps;
    public static var lights_fragment_end:Dynamic = lights_fragment_end;
    public static var logdepthbuf_fragment:Dynamic = logdepthbuf_fragment;
    public static var logdepthbuf_pars_fragment:Dynamic = logdepthbuf_pars_fragment;
    public static var logdepthbuf_pars_vertex:Dynamic = logdepthbuf_pars_vertex;
    public static var logdepthbuf_vertex:Dynamic = logdepthbuf_vertex;
    public static var map_fragment:Dynamic = map_fragment;
    public static var map_pars_fragment:Dynamic = map_pars_fragment;
    public static var map_particle_fragment:Dynamic = map_particle_fragment;
    public static var map_particle_pars_fragment:Dynamic = map_particle_pars_fragment;
    public static var metalnessmap_fragment:Dynamic = metalnessmap_fragment;
    public static var metalnessmap_pars_fragment:Dynamic = metalnessmap_pars_fragment;
    public static var morphinstance_vertex:Dynamic = morphinstance_vertex;
    public static var morphcolor_vertex:Dynamic = morphcolor_vertex;
    public static var morphnormal_vertex:Dynamic = morphnormal_vertex;
    public static var morphtarget_pars_vertex:Dynamic = morphtarget_pars_vertex;
    public static var morphtarget_vertex:Dynamic = morphtarget_vertex;
    public static var normal_fragment_begin:Dynamic = normal_fragment_begin;
    public static var normal_fragment_maps:Dynamic = normal_fragment_maps;
    public static var normal_pars_fragment:Dynamic = normal_pars_fragment;
    public static var normal_pars_vertex:Dynamic = normal_pars_vertex;
    public static var normal_vertex:Dynamic = normal_vertex;
    public static var normalmap_pars_fragment:Dynamic = normalmap_pars_fragment;
    public static var clearcoat_normal_fragment_begin:Dynamic = clearcoat_normal_fragment_begin;
    public static var clearcoat_normal_fragment_maps:Dynamic = clearcoat_normal_fragment_maps;
    public static var clearcoat_pars_fragment:Dynamic = clearcoat_pars_fragment;
    public static var iridescence_pars_fragment:Dynamic = iridescence_pars_fragment;
    public static var opaque_fragment:Dynamic = opaque_fragment;
    public static var packing:Dynamic = packing;
    public static var premultiplied_alpha_fragment:Dynamic = premultiplied_alpha_fragment;
    public static var project_vertex:Dynamic = project_vertex;
    public static var dithering_fragment:Dynamic = dithering_fragment;
    public static var dithering_pars_fragment:Dynamic = dithering_pars_fragment;
    public static var roughnessmap_fragment:Dynamic = roughnessmap_fragment;
    public static var roughnessmap_pars_fragment:Dynamic = roughnessmap_pars_fragment;
    public static var shadowmap_pars_fragment:Dynamic = shadowmap_pars_fragment;
    public static var shadowmap_pars_vertex:Dynamic = shadowmap_pars_vertex;
    public static var shadowmap_vertex:Dynamic = shadowmap_vertex;
    public static var shadowmask_pars_fragment:Dynamic = shadowmask_pars_fragment;
    public static var skinbase_vertex:Dynamic = skinbase_vertex;
    public static var skinning_pars_vertex:Dynamic = skinning_pars_vertex;
    public static var skinning_vertex:Dynamic = skinning_vertex;
    public static var skinnormal_vertex:Dynamic = skinnormal_vertex;
    public static var specularmap_fragment:Dynamic = specularmap_fragment;
    public static var specularmap_pars_fragment:Dynamic = specularmap_pars_fragment;
    public static var tonemapping_fragment:Dynamic = tonemapping_fragment;
    public static var tonemapping_pars_fragment:Dynamic = tonemapping_pars_fragment;
    public static var transmission_fragment:Dynamic = transmission_fragment;
    public static var transmission_pars_fragment:Dynamic = transmission_pars_fragment;
    public static var uv_pars_fragment:Dynamic = uv_pars_fragment;
    public static var uv_pars_vertex:Dynamic = uv_pars_vertex;
    public static var uv_vertex:Dynamic = uv_vertex;
    public static var worldpos_vertex:Dynamic = worldpos_vertex;

    public static var background_vert:Dynamic = background.vertex;
    public static var background_frag:Dynamic = background.fragment;
    public static var backgroundCube_vert:Dynamic = backgroundCube.vertex;
    public static var backgroundCube_frag:Dynamic = backgroundCube.fragment;
    public static var cube_vert:Dynamic = cube.vertex;
    public static var cube_frag:Dynamic = cube.fragment;
    public static var depth_vert:Dynamic = depth.vertex;
    public static var depth_frag:Dynamic = depth.fragment;
    public static var distanceRGBA_vert:Dynamic = distanceRGBA.vertex;
    public static var distanceRGBA_frag:Dynamic = distanceRGBA.fragment;
    public static var equirect_vert:Dynamic = equirect.vertex;
    public static var equirect_frag:Dynamic = equirect.fragment;
    public static var linedashed_vert:Dynamic = linedashed.vertex;
    public static var linedashed_frag:Dynamic = linedashed.fragment;
    public static var meshbasic_vert:Dynamic = meshbasic.vertex;
    public static var meshbasic_frag:Dynamic = meshbasic.fragment;
    public static var meshlambert_vert:Dynamic = meshlambert.vertex;
    public static var meshlambert_frag:Dynamic = meshlambert.fragment;
    public static var meshmatcap_vert:Dynamic = meshmatcap.vertex;
    public static var meshmatcap_frag:Dynamic = meshmatcap.fragment;
    public static var meshnormal_vert:Dynamic = meshnormal.vertex;
    public static var meshnormal_frag:Dynamic = meshnormal.fragment;
    public static var meshphong_vert:Dynamic = meshphong.vertex;
    public static var meshphong_frag:Dynamic = meshphong.fragment;
    public static var meshphysical_vert:Dynamic = meshphysical.vertex;
    public static var meshphysical_frag:Dynamic = meshphysical.fragment;
    public static var meshtoon_vert:Dynamic = meshtoon.vertex;
    public static var meshtoon_frag:Dynamic = meshtoon.fragment;
    public static var points_vert:Dynamic = points.vertex;
    public static var points_frag:Dynamic = points.fragment;
    public static var shadow_vert:Dynamic = shadow.vertex;
    public static var shadow_frag:Dynamic = shadow.fragment;
    public static var sprite_vert:Dynamic = sprite.vertex;
    public static var sprite_frag:Dynamic = sprite.fragment;
}
```