import haxe.xml.*;
import haxe.xml.Parser;
import haxe.xml.Printer;
import haxe.xml.XmlParserException;
import js.Browser;
import js.html.Document;
import js.html.Element;
import js.html.HTMLElement;
import js.html.HTMLCollection;
import js.html.HTMLDocument;
import js.html.HTMLImageElement;
import js.html.Window;
import js.Lib;
import js.Node;
import js.html.Node as DomNode;
import js.html._Document;
import js.html._Element;
import js.html._HTMLElement;
import js.html._HTMLCollection;
import js.html._HTMLDocument;
import js.html._Window;
import js.html._Node;
import js.html.event.Event;
import js.html.event.EventTarget;
import js.html.event.UIEvent;
import js.html.event.ProgressEvent;
import js.html.event.HashChangeEvent;
import js.html.event.PopStateEvent;
import js.html.event.StorageEvent;
import js.html.event.MouseEvent;
import js.html.event.WheelEvent;
import js.html.event.DragEvent;
import js.html.event.ClipboardEvent;
import js.html.event.KeyboardEvent;
import js.html.event.CompositionEvent;
import js.html.event.TouchEvent;
import js.html.event.FocusEvent;
import js.html.event.InputEvent;
import js.html.event.CloseEvent;
import js.html.event.ErrorEvent;
import js.html.event.MessageEvent;
import js.html.event.MediaStreamEvent;
import js.html.event.PageTransitionEvent;
import js.html.event.BeforeUnloadEvent;
import js.html.event.AbortPaymentEvent;
import js.html.event.CanMakePaymentEvent;
import js.html.event.PaymentRequestUpdateEvent;
import js.html.event.PaymentRequestEvent;
import js.html.event.AnimationEvent;
import js.html.event.TransitionEvent;
import js.html.event.DeviceMotionEvent;
import js.html.event.DeviceOrientationEvent;
import js.html.event.GamepadEvent;
import js.html.event.FullScreenEvent;
import js.html.event.PointerEvent;
import js.html.event.GotPointerCaptureEvent;
import js.html.event.LostPointerCaptureEvent;
import js.html.event.BeforePrintEvent;
import js.html.event.AfterPrintEvent;
import js.html.event.AudioProcessEvent;
import js.html.event.AudioNodeIOErrorEvent;
import js.html.event.AudioProcessingEvent;
import js.html.event.WebSocketPingEvent;
import js.html.event.WebSocketCloseEvent;
import js.html.event.RTCDataChannelEvent;
import js.html.event.RTCPeerConnectionIceEvent;
import js.html.event.MediaStreamTrackEvent;
import js.html.event.CloseEvent as MediaStreamCloseEvent;
import js.html.event.MediaStreamTrackEvent as MediaStreamTrackTrackEvent;
import js.html.event.MediaStreamEvent as MediaStreamStreamEvent;
import js.html.event.MediaStreamTrackEvent as MediaStreamSourceEvent;
import js.html.event.MediaEncryptedEvent;
import js.html.event.MediaKeyMessageEvent;
import js.html.event.MediaKeyNeededEvent;
import js.html.event.MediaKeyMessageEvent as EncryptedMediaKeyMessageEvent;
import js.html.event.MediaKeyNeededEvent as EncryptedMediaKeyNeededEvent;
import js.html.event.MediaEncryptedEvent as EncryptedMediaEncryptedEvent;
import js.html.event.TimeEvent;
import js.html.event.TimeEvent as EncryptedTimeEvent;
import js.html.event.TimeEvent as MediaEncryptedTimeEvent;
import js.html.event.TimeEvent as MediaKeyMessageTimeEvent;
import js.html.event.TimeEvent as MediaKeyNeededTimeEvent;
import js.html.performance.Performance;
import js.html.performance.PerformanceEntry;
import js.html.performance.PerformanceMark;
import js.html.performance.PerformanceMeasure;
import js.html.performance.PerformanceResourceTiming;
import js.html.performance.PerformanceNavigation;
import js.html.performance.PerformanceTiming;
import js.html.performance.PerformanceObserver;
import js.html.performance.PerformanceObserverEntryList;
import js.html.performance.PerformanceObserverEntry;
import js.html.performance.PerformanceFrameTiming;
import js.html.performance.PerformancePaintTiming;
import js.___PerformanceServerTiming;
import js.html.performance.PerformanceServerTiming;
import js.html.performance.PerformanceLongTaskTiming;
import js.html.performance.PerformanceElementTiming;
import js.html.performance.PerformanceNavigationTiming;
import js.html.performance.PerformanceNavigationTiming as PerformanceNavigationType;
import js.html.performance.PerformanceResourceTiming as PerformanceResourceTimingType;
import js.html.performance.PerformanceServerTiming as PerformanceServerTimingType;
import js.html.performance.PerformanceLongTaskTiming as PerformanceLongTaskTimingType;
import js.html.performance.PerformanceElementTiming as PerformanceElementTimingType;
import js.html.performance.PerformanceFrameTiming as PerformanceFrameTimingType;
import js.html.performance.PerformancePaintTiming as PerformancePaintTimingType;
import js.html.performance.Performance;
import js.html.performance.PerformanceTiming as PerformanceTimingType;
import js.html.performance.PerformanceEntry as PerformanceEntryType;
import js.html.performance.PerformanceMark as PerformanceMarkType;
import js.html.performance.PerformanceMeasure as PerformanceMeasureType;
import js.html.performance.PerformanceResourceTiming as PerformanceResourceTimingEntry;
import js.html.performance.PerformanceNavigation as PerformanceNavigationEntry;
import js.html.performance.PerformanceObserver as PerformanceObserverType;
import js.html.performance.PerformanceObserverEntryList as PerformanceObserverEntryListType;
import js.html.performance.PerformanceObserverEntry as PerformanceObserverEntryType;
import js.html.performance.PerformanceFrameTiming as PerformanceFrameTimingEntry;
import js.html.performance.PerformancePaintTiming as PerformancePaintTimingEntry;
import js.html.performance.PerformanceServerTiming as PerformanceServerTimingEntry;
import js.html.performance.PerformanceLongTaskTiming as PerformanceLongTaskTimingEntry;
import js.html.performance.PerformanceElementTiming as PerformanceElementTimingEntry;
import js.html.performance.PerformanceNavigationTiming as PerformanceNavigationTimingEntry;
import js.html.performance.PerformanceResourceTiming as PerformanceResourceTimingTiming;
import js.html.performance.PerformanceServerTiming as PerformanceServerTimingTiming;
import js.html.performance.PerformanceLongTaskTiming as PerformanceLongTaskTimingTiming;
import js.html.performance.PerformanceElementTiming as PerformanceElementTimingTiming;
import js.html.performance.PerformanceFrameTiming as PerformanceFrameTimingTiming;
import js.html.performance.PerformancePaintTiming as PerformancePaintTimingTiming;
import js.html.performance.Performance;
import js.html.performance.PerformanceTiming as PerformanceTimingTiming;
import js.html.performance.PerformanceEntry as PerformanceEntryTiming;
import js.html.performance.PerformanceMark as PerformanceMarkTiming;
import js.html.performance.PerformanceMeasure as PerformanceMeasureTiming;
import js.html.performance.PerformanceResourceTiming as PerformanceResourceTimingTypeTiming;
import js.html.performance.PerformanceNavigation as PerformanceNavigationTypeTiming;
import js.html.performance.PerformanceObserver as PerformanceObserverTiming;
import js.html.performance.PerformanceObserverEntryList as PerformanceObserverEntryListTiming;
import js.html.performance.PerformanceObserverEntry as PerformanceObserverEntryTiming;
import js.html.performance.PerformanceFrameTiming as PerformanceFrameTimingTypeTiming;
import js.html.performance.PerformancePaintTiming as PerformancePaintTimingTypeTiming;
import js.html.performance.PerformanceServerTiming as PerformanceServerTimingTypeTiming;
import js.html.performance.PerformanceLongTaskTiming as PerformanceLongTaskTimingTypeTiming;
import js.html.performance.PerformanceElementTiming as PerformanceElementTimingTypeTiming;
import js.html.performance.PerformanceNavigationTiming as PerformanceNavigationTimingTypeTiming;
import js.html.performance.PerformanceResourceTiming as PerformanceResourceTimingTimingTiming;
import js.html.performance.PerformanceServerTiming as PerformanceServerTimingTimingTiming;
import js.html.performance.PerformanceLongTaskTiming as PerformanceLongTaskTimingTimingTiming;
import js.html.performance.PerformanceElementTiming as PerformanceElementTimingTimingTiming;
import js.html.performance.PerformanceFrameTiming as PerformanceFrameTimingTimingTiming;
import js.html.performance.PerformancePaintTiming as PerformancePaintTimingTimingTiming;
import js.html.performance.PerformanceServerTiming as PerformanceServerTimingEntryTiming;
import js.html.performance.PerformanceLongTaskTiming as PerformanceLongTaskTimingEntryTiming;
import js.html.performance.PerformanceElementTiming as PerformanceElementTimingEntryTiming;
import js.html.performance.PerformanceNavigationTiming as PerformanceNavigationTimingEntryTiming;
import js.html.performance.PerformanceResourceTiming as PerformanceResourceTimingTimingTiming;
import js.html.performance.PerformanceServerTiming as PerformanceServerTimingTimingTiming;
import js.html.performance.PerformanceLongTaskTiming as PerformanceLongTaskTimingTimingTiming;
import js.html.performance.PerformanceElementTiming as PerformanceElementTimingTimingTiming;
import js.html.performance.PerformanceFrameTiming as PerformanceFrameTimingTimingTiming;
import js.html.performance.PerformancePaintTiming as PerformancePaintTimingTimingTiming;
import js.html.performance.PerformanceServerTiming as PerformanceServerTimingTypeTiming;
import js.html.performance.PerformanceLongTaskTiming as PerformanceLongTaskTimingTypeTiming;
import js.html.performance.PerformanceElementTiming as PerformanceElementTimingTypeTiming;
import js.html.performance.PerformanceNavigationTiming as PerformanceNavigationTypeTiming;
import js.html.performance.PerformanceResourceTiming as PerformanceResourceTimingType;
import js.html.performance.PerformanceObserver as PerformanceObserverType;
import js.html.performance.PerformanceObserverEntryList as PerformanceObserverEntryListType;
import js.html.performance.PerformanceObserverEntry as PerformanceObserverEntryType;
import js.html.performance.PerformanceFrameTiming as PerformanceFrameTimingType;
import js.html.performance.PerformancePaintTiming as PerformancePaintTimingType;
import js.html.performance.Performance;
import js.html.performance.PerformanceTiming as PerformanceTimingType;
import js.html.performance.PerformanceEntry as PerformanceEntryType;
import js.html.performance.PerformanceMark as PerformanceMarkType;
import js.html.performance.PerformanceMeasure as PerformanceMeasureType;
import js.html.performance.PerformanceResourceTiming as PerformanceResourceTimingEntry;
import js.html.performance.PerformanceNavigation as PerformanceNavigationEntry;
import js.html.performance.PerformanceObserver as PerformanceObserverTiming;
import js.html.performance.PerformanceObserverEntryList as PerformanceObserverEntryListTiming;
import js.html.performance.PerformanceObserverEntry as PerformanceObserverEntryTiming;
import js.html.performance.PerformanceFrameTiming as PerformanceFrameTimingTiming;
import js.html.performance.PerformancePaintTiming as PerformancePaintTimingTiming;
import js.html.performance.PerformanceServerTiming as PerformanceServerTimingTiming;
import js.html.performance.PerformanceLongTaskTiming as PerformanceLongTaskTimingTiming;
import js.html.performance.PerformanceElementTiming as PerformanceElementTimingTiming;
import js.html.performance.PerformanceNavigationTiming as PerformanceNavigationTimingTiming;
import js.html.performance.PerformanceResourceTiming as PerformanceResourceTimingTiming;
import js.html.performance.PerformanceServerTiming as PerformanceServerTimingTiming;
import js.html.performance.PerformanceLongTaskTiming as PerformanceLongTaskTimingTiming;
import js.html.performance.PerformanceElementTiming as PerformanceElementTimingTiming;
import js.html.performance.PerformanceFrameTiming as PerformanceFrameTimingTiming;
import js.html.performance.PerformancePaintTiming as PerformancePaintTimingTiming;
import js.html.performance.PerformanceServerTiming as PerformanceServerTimingTypeTiming;
import js.html.performance.PerformanceLongTaskTiming as PerformanceLongTaskTimingTypeTiming;
import js.html.performance.PerformanceElementTiming as PerformanceElementTimingTypeTiming;
import js.html.performance.PerformanceNavigationTiming as PerformanceNavigationTypeTiming;
import js.html.performance.PerformanceResourceTiming as PerformanceResourceTimingType;
import js.html.performance.PerformanceObserver as PerformanceObserverType;
import js.html.performance.PerformanceObserverEntryList as PerformanceObserverEntryListType;
import js.html.performance.PerformanceObserverEntry as PerformanceObserverEntryType;
import js.html.performance.PerformanceFrameTiming as PerformanceFrameTimingType;
import js.html.performance.PerformancePaintTiming as PerformancePaintTimingType;
import js.html.performance.Performance;
import js.html.performance.PerformanceTiming as PerformanceTimingType;
import js.html.performance.PerformanceEntry as PerformanceEntryType;
import js.html.performance.PerformanceMark as PerformanceMarkType;
import js.html.performance.PerformanceMeasure as PerformanceMeasureType;
import js.html.performance.PerformanceResourceTiming as PerformanceResourceTimingEntry;
import js.html.performance.PerformanceNavigation as PerformanceNavigationEntry;
import js.html.performance.PerformanceObserver as PerformanceObserverTiming;
import js.html.performance.PerformanceObserverEntryList as PerformanceObserverEntryListTiming;
import js.html.performance.PerformanceObserverEntry as PerformanceObserverEntryTiming;
import js.html.performance.PerformanceFrameTiming as PerformanceFrameTimingTiming;
import js.html.performance.PerformancePaintTiming as PerformancePaintTimingTiming;
import js.html.performance.PerformanceServerTiming as PerformanceServerTimingTiming;
import js.html.performance.PerformanceLongTaskTiming as PerformanceLongTaskTimingTiming;
import js.html.performance.PerformanceElementTiming as PerformanceElementTimingTiming;
import js.html.performance.PerformanceNavigationTiming as PerformanceNavigationTimingTiming;
import js.html.performance.PerformanceResourceTiming as PerformanceResourceTimingTiming;
import js.html.performance.PerformanceServerTiming as PerformanceServerTimingTiming;
import js.html.performance.PerformanceLongTaskTiming as PerformanceLongTaskTimingTiming;
import js.html.performance.PerformanceElementTiming as PerformanceElementTimingTiming;
import js.html.performance.PerformanceFrameTiming as PerformanceFrameTimingTiming;
import js.html.performance.PerformancePaintTiming as PerformancePaintTimingTiming;
import js.html.performance.PerformanceServerTiming as PerformanceServerTimingTypeTiming;
import js.html.performance.PerformanceLongTaskTiming as PerformanceLongTaskTimingTypeTiming;
import js.html.performance.PerformanceElementTiming as PerformanceElementTimingTypeTiming;
import js.html.performance.PerformanceNavigationTiming as PerformanceNavigationTypeTiming;
import js.html.performance.PerformanceResourceTiming as PerformanceResourceTimingType;
import js.html.performance.PerformanceObserver as PerformanceObserverType;
import js.html.performance.PerformanceObserverEntryList as PerformanceObserverEntryListType;
import js.html.performance.PerformanceObserverEntry as PerformanceObserverEntryType;
import js.html.performance.PerformanceFrameTiming as PerformanceFrameTimingType;
import js.html.performance.PerformancePaintTiming as PerformancePaintTimingType;
import js.html.performance.Performance;
import js.html.performance.PerformanceTiming as PerformanceTimingType;
import js.html.performance.PerformanceEntry as PerformanceEntryType;
import js.html.performance.PerformanceMark as PerformanceMarkType;
import js.html.performance.PerformanceMeasure as PerformanceMeasureType;
import js.html.performance.PerformanceResourceTiming as PerformanceResourceTimingEntry;
import js.html.performance.PerformanceNavigation as PerformanceNavigationEntry;
import js.html.performance.PerformanceObserver as PerformanceObserverTiming;
import js.html.performance.PerformanceObserverEntryList as PerformanceObserverEntryListTiming;
import js.html.performance.PerformanceObserverEntry as PerformanceObserverEntryTiming;
import js.html.performance.PerformanceFrameTiming as PerformanceFrameTimingTiming;
import js.html.performance.PerformancePaintTiming as PerformancePaintTimingTiming;
import js.html.performance.PerformanceServerTiming as PerformanceServerTimingTiming;
import js.html.performance.PerformanceLongTaskTiming as PerformanceLongTaskTimingTiming;
import js.html.performance.PerformanceElementTiming as PerformanceElementTimingTiming;
import js.html.performance.PerformanceNavigationTiming as PerformanceNavigationTimingTiming;
import js.html.performance.PerformanceResourceTiming as PerformanceResourceTimingTiming;
import js.html.performance.PerformanceServerTiming as PerformanceServerTimingTiming;
import js.html.performance.PerformanceLongTaskTiming as PerformanceLongTaskTimingTiming;
import js.html.performance.PerformanceElementTiming as PerformanceElementTimingTiming;
import js.html.performance.PerformanceFrameTiming as PerformanceFrameTimingTiming;
import js.html.performance.PerformancePaintTiming as PerformancePaintTimingTiming;
import js.html.performance.PerformanceServerTiming as PerformanceServerTimingTypeTiming;
import js.html.performance.PerformanceLongTaskTiming as PerformanceLongTaskTimingTypeTiming;
import js.html.performance.PerformanceElementTiming as PerformanceElementTimingTypeTiming;
import js.html.performance.PerformanceNavigationTiming as PerformanceNavigationTypeTiming;
import js.html.performance.PerformanceResourceTiming as PerformanceResourceTimingType;
import js.html.performance.PerformanceObserver as PerformanceObserverType;
import js.html.performance.PerformanceObserverEntryList as PerformanceObserverEntryListType;
import js.html.performance.PerformanceObserverEntry as PerformanceObserverEntryType;
import js.html.performance.PerformanceFrameTiming as PerformanceFrameTimingType;
import js.html.performance.PerformancePaintTiming as PerformancePaintTimingType;
import js.html.performance.Performance;
import js.html.performance.PerformanceTiming as PerformanceTimingType;
import js.html.performance.PerformanceEntry as