class Constants {

    static public var REVISION:String = '165dev';

    static public var MOUSE:haxe.ds.StringMap = new haxe.ds.StringMap();
    static public var TOUCH:haxe.ds.StringMap = new haxe.ds.StringMap();

    static function init() {
        MOUSE.set('LEFT', 0);
        MOUSE.set('MIDDLE', 1);
        MOUSE.set('RIGHT', 2);
        MOUSE.set('ROTATE', 0);
        MOUSE.set('DOLLY', 1);
        MOUSE.set('PAN', 2);

        TOUCH.set('ROTATE', 0);
        TOUCH.set('PAN', 1);
        TOUCH.set('DOLLY_PAN', 2);
        TOUCH.set('DOLLY_ROTATE', 3);
    }

    static public var CullFaceNone:Int = 0;
    static public var CullFaceBack:Int = 1;
    static public var CullFaceFront:Int = 2;
    static public var CullFaceFrontBack:Int = 3;
    static public var BasicShadowMap:Int = 0;
    static public var PCFShadowMap:Int = 1;
    static public var PCFSoftShadowMap:Int = 2;
    static public var VSMShadowMap:Int = 3;
    static public var FrontSide:Int = 0;
    static public var BackSide:Int = 1;
    static public var DoubleSide:Int = 2;
    static public var NoBlending:Int = 0;
    static public var NormalBlending:Int = 1;
    static public var AdditiveBlending:Int = 2;
    static public var SubtractiveBlending:Int = 3;
    static public var MultiplyBlending:Int = 4;
    static public var CustomBlending:Int = 5;
    static public var AddEquation:Int = 100;
    static public var SubtractEquation:Int = 101;
    static public var ReverseSubtractEquation:Int = 102;
    static public var MinEquation:Int = 103;
    static public var MaxEquation:Int = 104;
    static public var ZeroFactor:Int = 200;
    static public var OneFactor:Int = 201;
    static public var SrcColorFactor:Int = 202;
    static public var OneMinusSrcColorFactor:Int = 203;
    static public var SrcAlphaFactor:Int = 204;
    static public var OneMinusSrcAlphaFactor:Int = 205;
    static public var DstAlphaFactor:Int = 206;
    static public var OneMinusDstAlphaFactor:Int = 207;
    static public var DstColorFactor:Int = 208;
    static public var OneMinusDstColorFactor:Int = 209;
    static public var SrcAlphaSaturateFactor:Int = 210;
    static public var ConstantColorFactor:Int = 211;
    static public var OneMinusConstantColorFactor:Int = 212;
    static public var ConstantAlphaFactor:Int = 213;
    static public var OneMinusConstantAlphaFactor:Int = 214;
    static public var NeverDepth:Int = 0;
    static public var AlwaysDepth:Int = 1;
    static public var LessDepth:Int = 2;
    static public var LessEqualDepth:Int = 3;
    static public var EqualDepth:Int = 4;
    static public var GreaterEqualDepth:Int = 5;
    static public var GreaterDepth:Int = 6;
    static public var NotEqualDepth:Int = 7;
    static public var MultiplyOperation:Int = 0;
    static public var MixOperation:Int = 1;
    static public var AddOperation:Int = 2;
    static public var NoToneMapping:Int = 0;
    static public var LinearToneMapping:Int = 1;
    static public var ReinhardToneMapping:Int = 2;
    static public var CineonToneMapping:Int = 3;
    static public var ACESFilmicToneMapping:Int = 4;
    static public var CustomToneMapping:Int = 5;
    static public var AgXToneMapping:Int = 6;
    static public var NeutralToneMapping:Int = 7;
    static public var AttachedBindMode:String = 'attached';
    static public var DetachedBindMode:String = 'detached';

    static public var UVMapping:Int = 300;
    static public var CubeReflectionMapping:Int = 301;
    static public var CubeRefractionMapping:Int = 302;
    static public var EquirectangularReflectionMapping:Int = 303;
    static public var EquirectangularRefractionMapping:Int = 304;
    static public var CubeUVReflectionMapping:Int = 306;
    static public var RepeatWrapping:Int = 1000;
    static public var ClampToEdgeWrapping:Int = 1001;
    static public var MirroredRepeatWrapping:Int = 1002;
    static public var NearestFilter:Int = 1003;
    static public var NearestMipmapNearestFilter:Int = 1004;
    static public var NearestMipMapNearestFilter:Int = 1004;
    static public var NearestMipmapLinearFilter:Int = 1005;
    static public var NearestMipMapLinearFilter:Int = 1005;
    static public var LinearFilter:Int = 1006;
    static public var LinearMipmapNearestFilter:Int = 1007;
    static public var LinearMipMapNearestFilter:Int = 1007;
    static public var LinearMipmapLinearFilter:Int = 1008;
    static public var LinearMipMapLinearFilter:Int = 1008;
    static public var UnsignedByteType:Int = 1009;
    static public var ByteType:Int = 1010;
    static public var ShortType:Int = 1011;
    static public var UnsignedShortType:Int = 1012;
    static public var IntType:Int = 1013;
    static public var UnsignedIntType:Int = 1014;
    static public var FloatType:Int = 1015;
    static public var HalfFloatType:Int = 1016;
    static public var UnsignedShort4444Type:Int = 1017;
    static public var UnsignedShort5551Type:Int = 1018;
    static public var UnsignedInt248Type:Int = 1020;
    static public var UnsignedInt5999Type:Int = 35902;
    static public var AlphaFormat:Int = 1021;
    static public var RGBFormat:Int = 1022;
    static public var RGBAFormat:Int = 1023;
    static public var LuminanceFormat:Int = 1024;
    static public var LuminanceAlphaFormat:Int = 1025;
    static public var DepthFormat:Int = 1026;
    static public var DepthStencilFormat:Int = 1027;
    static public var RedFormat:Int = 1028;
    static public var RedIntegerFormat:Int = 1029;
    static public var RGFormat:Int = 1030;
    static public var RGIntegerFormat:Int = 1031;
    static public var RGBAIntegerFormat:Int = 1033;

    static public var RGB_S3TC_DXT1_Format:Int = 33776;
    static public var RGBA_S3TC_DXT1_Format:Int = 33777;
    static public var RGBA_S3TC_DXT3_Format:Int = 33778;
    static public var RGBA_S3TC_DXT5_Format:Int = 33779;
    static public var RGB_PVRTC_4BPPV1_Format:Int = 35840;
    static public var RGB_PVRTC_2BPPV1_Format:Int = 35841;
    static public var RGBA_PVRTC_4BPPV1_Format:Int = 35842;
    static public var RGBA_PVRTC_2BPPV1_Format:Int = 35843;
    static public var RGB_ETC1_Format:Int = 36196;
    static public var RGB_ETC2_Format:Int = 37492;
    static public var RGBA_ETC2_EAC_Format:Int = 37496;
    static public var RGBA_ASTC_4x4_Format:Int = 37808;
    static public var RGBA_ASTC_5x4_Format:Int = 37809;
    static public var RGBA_ASTC_5x5_Format:Int = 37810;
    static public var RGBA_ASTC_6x5_Format:Int = 37811;
    static public var RGBA_ASTC_6x6_Format:Int = 37812;
    static public var RGBA_ASTC_8x5_Format:Int = 37813;
    static public var RGBA_ASTC_8x6_Format:Int = 37814;
    static public var RGBA_ASTC_8x8_Format:Int = 37815;
    static public var RGBA_ASTC_10x5_Format:Int = 37816;
    static public var RGBA_ASTC_10x6_Format:Int = 37817;
    static public var RGBA_ASTC_10x8_Format:Int = 37818;
    static public var RGBA_ASTC_10x10_Format:Int = 37819;
    static public var RGBA_ASTC_12x10_Format:Int = 37820;
    static public var RGBA_ASTC_12x12_Format:Int = 37821;
    static public var RGBA_BPTC_Format:Int = 36492;
    static public var RGB_BPTC_SIGNED_Format:Int = 36494;
    static public var RGB_BPTC_UNSIGNED_Format:Int = 36495;
    static public var RED_RGTC1_Format:Int = 36283;
    static public var SIGNED_RED_RGTC1_Format:Int = 36284;
    static public var RED_GREEN_RGTC2_Format:Int = 36285;
    static public var SIGNED_RED_GREEN_RGTC2_Format:Int = 36286;
    static public var LoopOnce:Int = 2200;
    static public var LoopRepeat:Int = 2201;
    static public var LoopPingPong:Int = 2202;
    static public var InterpolateDiscrete:Int = 2300;
    static public var InterpolateLinear:Int = 2301;
    static public var InterpolateSmooth:Int = 2302;
    static public var ZeroCurvatureEnding:Int = 2400;
    static public var ZeroSlopeEnding:Int = 2401;
    static public var WrapAroundEnding:Int = 2402;
    static public var NormalAnimationBlendMode:Int = 2500;
    static public var AdditiveAnimationBlendMode:Int = 2501;
    static public var TrianglesDrawMode:Int = 0;
    static public var TriangleStripDrawMode:Int = 1;
    static public var TriangleFanDrawMode:Int = 2;
    static public var BasicDepthPacking:Int = 3200;
    static public var RGBADepthPacking:Int = 3201;
    static public var TangentSpaceNormalMap:Int = 0;
    static public var ObjectSpaceNormalMap:Int = 1;

    static public var NoColorSpace:String = '';
    static public var SRGBColorSpace:String = 'srgb';
    static public var LinearSRGBColorSpace:String = 'srgb-linear';
    static public var DisplayP3ColorSpace:String = 'display-p3';
    static public var LinearDisplayP3ColorSpace:String = 'display-p3-linear';

    static public var LinearTransfer:String = 'linear';
    static public var SRGBTransfer:String = 'srgb';

    static public var Rec709Primaries:String = 'rec709';
    static public var P3Primaries:String = 'p3';

    static public var ZeroStencilOp:Int = 0;
    static public var KeepStencilOp:Int = 7680;
    static public var ReplaceStencilOp:Int = 7681;
    static public var IncrementStencilOp:Int = 7682;
    static public var DecrementStencilOp:Int = 7683;
    static public var IncrementWrapStencilOp:Int = 34055;
    static public var DecrementWrapStencilOp:Int = 34056;
    static public var InvertStencilOp:Int = 5386;

    static public var NeverStencilFunc:Int = 512;
    static public var LessStencilFunc:Int = 513;
    static public var EqualStencilFunc:Int = 514;
    static public var LessEqualStencilFunc:Int = 515;
    static public var GreaterStencilFunc:Int = 516;
    static public var NotEqualStencilFunc:Int = 517;
    static public var GreaterEqualStencilFunc:Int = 518;
    static public var AlwaysStencilFunc:Int = 519;

    static public var NeverCompare:Int = 512;
    static public var LessCompare:Int = 513;
    static public var EqualCompare:Int = 514;
    static public var LessEqualCompare:Int = 515;
    static public var GreaterCompare:Int = 516;
    static public var NotEqualCompare:Int = 517;
    static public var GreaterEqualCompare:Int = 518;
    static public var AlwaysCompare:Int = 519;

    static public var StaticDrawUsage:Int = 35044;
    static public var DynamicDrawUsage:Int = 35048;
    static public var StreamDrawUsage:Int = 35040;
    static public var StaticReadUsage:Int = 35045;
    static public var DynamicReadUsage:Int = 35049;
    static public var StreamReadUsage:Int = 35041;
    static public var StaticCopyUsage:Int = 35046;
    static public var DynamicCopyUsage:Int = 35050;
    static public var StreamCopyUsage:Int = 35042;

    static public var GLSL1:String = '100';
    static public var GLSL3:String = '300 es';

    static public var WebGLCoordinateSystem:Int = 2000;
    static public var WebGPUCoordinateSystem:Int = 2001;
}